-- Element Fleet Services dynamic-table-based DIM_MAINTENANCE_VENDOR population.
-- Run after `element_fleet_snowflake_sit_setup.sql` has created the ADLS stage
-- and file format in FLEET_MVP_SIT.
--
-- Purpose:
--   ADLS STAGING Parquet -> STG_FLEET.MAINTENANCE_VENDORS_EXT
--   -> STG_FLEET.MAINTENANCE_VENDORS_HISTORY
--   -> STG_FLEET.MAINTENANCE_VENDORS_ELIGIBLE_DT
--   -> CONFORMED.DIM_MAINTENANCE_VENDOR
--
-- Snowflake dynamic tables cannot use external tables as direct sources. This
-- pattern therefore uses a controlled internal history table as the dynamic
-- table source. It is a good fit for small/medium reference dimensions where
-- the complete source versions needed for history are available in staged
-- extract history.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FLEET_MVP_SIT_WH;
USE DATABASE FLEET_MVP_SIT;

CREATE SCHEMA IF NOT EXISTS STG_FLEET;
CREATE SCHEMA IF NOT EXISTS CONFORMED;
CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.MAINTENANCE_VENDORS_EXT (
  VENDOR_ID VARCHAR AS (VALUE:vendor_id::VARCHAR),
  VENDOR_NAME VARCHAR AS (VALUE:vendor_name::VARCHAR),
  VENDOR_TYPE VARCHAR AS (VALUE:vendor_type::VARCHAR),
  STATE VARCHAR AS (VALUE:state::VARCHAR),
  PREFERRED_VENDOR_FLAG VARCHAR AS (VALUE:preferred_vendor_flag::VARCHAR),
  AVERAGE_APPROVAL_HOURS NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:average_approval_hours::VARCHAR, 18, 2)),
  MONTHLY_CAPACITY_JOBS NUMBER AS (TRY_TO_NUMBER(VALUE:monthly_capacity_jobs::VARCHAR)),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  _LOAD_TYPE VARCHAR AS (VALUE:_load_type::VARCHAR),
  _SOURCE_EXTRACT_DATE DATE AS (TRY_TO_DATE(VALUE:_source_extract_date::VARCHAR)),
  _DELTA_ACTION VARCHAR AS (VALUE:_delta_action::VARCHAR),
  _BATCH_DATE DATE AS (TRY_TO_DATE(VALUE:_batch_date::VARCHAR)),
  _RECORD_HASH VARCHAR AS (VALUE:_record_hash::VARCHAR),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=maintenance_vendors/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

ALTER EXTERNAL TABLE STG_FLEET.MAINTENANCE_VENDORS_EXT REFRESH;

CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.MAINTENANCE_VENDORS_HISTORY AS
SELECT *
FROM STG_FLEET.MAINTENANCE_VENDORS_EXT;

CREATE OR REPLACE DYNAMIC TABLE STG_FLEET.MAINTENANCE_VENDORS_ELIGIBLE_DT
  TARGET_LAG = '1 minute'
  WAREHOUSE = FLEET_MVP_SIT_WH
AS
SELECT
  VENDOR_ID,
  VENDOR_NAME,
  VENDOR_TYPE,
  STATE,
  PREFERRED_VENDOR_FLAG,
  AVERAGE_APPROVAL_HOURS,
  MONTHLY_CAPACITY_JOBS,
  EFFECTIVE_AT,
  UPDATED_AT,
  _BATCH_DATE,
  _LOAD_TYPE,
  _SOURCE_EXTRACT_DATE,
  _DELTA_ACTION,
  _RECORD_HASH
FROM STG_FLEET.MAINTENANCE_VENDORS_HISTORY
WHERE _IS_LATEST_FOR_BUSINESS_KEY = TRUE
  AND _LATEST_RESOLUTION_STATUS = 'resolved'
  AND _IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(_DQ_STATUS, 'passed') = 'passed'
  AND COALESCE(_DELTA_ACTION, 'UPSERT') <> 'DELETE';

CREATE OR REPLACE DYNAMIC TABLE CONFORMED.DIM_MAINTENANCE_VENDOR
  TARGET_LAG = '1 minute'
  WAREHOUSE = FLEET_MVP_SIT_WH
AS
WITH version_candidates AS (
  SELECT
    VENDOR_ID,
    VENDOR_NAME,
    VENDOR_TYPE,
    STATE,
    PREFERRED_VENDOR_FLAG,
    AVERAGE_APPROVAL_HOURS,
    MONTHLY_CAPACITY_JOBS,
    EFFECTIVE_AT,
    UPDATED_AT,
    _BATCH_DATE,
    _RECORD_HASH,
    LAG(_RECORD_HASH) OVER (
      PARTITION BY VENDOR_ID
      ORDER BY _BATCH_DATE, UPDATED_AT, EFFECTIVE_AT, _RECORD_HASH
    ) AS PREVIOUS_RECORD_HASH
  FROM STG_FLEET.MAINTENANCE_VENDORS_ELIGIBLE_DT
),
change_points AS (
  SELECT *
  FROM version_candidates
  WHERE PREVIOUS_RECORD_HASH IS NULL
     OR PREVIOUS_RECORD_HASH <> _RECORD_HASH
),
scd_versions AS (
  SELECT
    ROW_NUMBER() OVER (ORDER BY VENDOR_ID, EFFECTIVE_AT, UPDATED_AT, _RECORD_HASH) AS VENDOR_SK,
    VENDOR_ID,
    VENDOR_NAME,
    VENDOR_TYPE,
    STATE,
    PREFERRED_VENDOR_FLAG,
    AVERAGE_APPROVAL_HOURS,
    MONTHLY_CAPACITY_JOBS,
    VENDOR_ID AS BUSINESS_KEY,
    EFFECTIVE_AT AS EFFECTIVE_FROM,
    COALESCE(
      LEAD(EFFECTIVE_AT) OVER (
        PARTITION BY VENDOR_ID
        ORDER BY _BATCH_DATE, UPDATED_AT, EFFECTIVE_AT, _RECORD_HASH
      ),
      '9999-12-31'::TIMESTAMP_NTZ
    ) AS EFFECTIVE_TO,
    IFF(
      LEAD(EFFECTIVE_AT) OVER (
        PARTITION BY VENDOR_ID
        ORDER BY _BATCH_DATE, UPDATED_AT, EFFECTIVE_AT, _RECORD_HASH
      ) IS NULL,
      TRUE,
      FALSE
    ) AS IS_CURRENT,
    FALSE AS DELETED_FLAG,
    EFFECTIVE_AT AS SOURCE_EFFECTIVE_AT,
    UPDATED_AT AS SOURCE_UPDATED_AT,
    _RECORD_HASH AS SOURCE_RECORD_HASH,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
  FROM change_points
)
SELECT *
FROM scd_versions;

ALTER DYNAMIC TABLE STG_FLEET.MAINTENANCE_VENDORS_ELIGIBLE_DT REFRESH;
ALTER DYNAMIC TABLE CONFORMED.DIM_MAINTENANCE_VENDOR REFRESH;

CREATE TABLE IF NOT EXISTS AUDIT.SIT_CHECK_RESULTS (
  CHECK_NAME VARCHAR,
  CHECK_VALUE NUMBER,
  EXPECTED_VALUE NUMBER,
  CHECK_STATUS VARCHAR,
  CHECKED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT
  'DIM_MAINT_VENDOR_CURRENT_ROWS_DYNAMIC',
  COUNT(*),
  23,
  IFF(COUNT(*) = 23, 'passed', 'failed')
FROM CONFORMED.DIM_MAINTENANCE_VENDOR
WHERE IS_CURRENT = TRUE;

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT
  'DIM_MAINT_VENDOR_CLOSED_CHANGED_ROWS_DYNAMIC',
  COUNT(*),
  8,
  IFF(COUNT(*) = 8, 'passed', 'failed')
FROM CONFORMED.DIM_MAINTENANCE_VENDOR
WHERE IS_CURRENT = FALSE
  AND DELETED_FLAG = FALSE;

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT
  'DIM_MAINT_VENDOR_SOFT_DELETED_ROWS_DYNAMIC',
  COUNT(*),
  0,
  IFF(COUNT(*) = 0, 'passed', 'failed')
FROM CONFORMED.DIM_MAINTENANCE_VENDOR
WHERE DELETED_FLAG = TRUE;

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
WITH duplicate_current AS (
  SELECT VENDOR_ID
  FROM CONFORMED.DIM_MAINTENANCE_VENDOR
  WHERE IS_CURRENT = TRUE
  GROUP BY VENDOR_ID
  HAVING COUNT(*) > 1
)
SELECT
  'DIM_MAINT_VENDOR_DUPLICATE_CURRENT_DYNAMIC',
  COUNT(*),
  0,
  IFF(COUNT(*) = 0, 'passed', 'failed')
FROM duplicate_current;

SELECT *
FROM AUDIT.SIT_CHECK_RESULTS
WHERE CHECK_NAME LIKE 'DIM_MAINT_VENDOR%DYNAMIC'
ORDER BY CHECKED_AT, CHECK_NAME;

SELECT
  VENDOR_ID,
  VENDOR_NAME,
  VENDOR_TYPE,
  STATE,
  PREFERRED_VENDOR_FLAG,
  EFFECTIVE_FROM,
  EFFECTIVE_TO,
  IS_CURRENT,
  DELETED_FLAG
FROM CONFORMED.DIM_MAINTENANCE_VENDOR
WHERE VENDOR_ID IN (
  SELECT D1.VENDOR_ID
  FROM STG_FLEET.MAINTENANCE_VENDORS_HISTORY D1
  JOIN STG_FLEET.MAINTENANCE_VENDORS_HISTORY D2
    ON D2.VENDOR_ID = D1.VENDOR_ID
   AND D2._BATCH_DATE = '2026-05-26'
  WHERE D1._BATCH_DATE = '2026-05-25'
    AND D1._RECORD_HASH <> D2._RECORD_HASH
)
ORDER BY VENDOR_ID, EFFECTIVE_FROM;
