-- Element Fleet Services MVP Snowflake SQL.
-- Python/Fabric prepares ADLS RAW and ADLS STAGING. Snowflake SQL owns deterministic
-- warehouse modelling from STG_FLEET into CONFORMED.

CREATE SCHEMA IF NOT EXISTS STG_FLEET;
CREATE SCHEMA IF NOT EXISTS CONFORMED;
CREATE SCHEMA IF NOT EXISTS AUDIT;

-- Controlled load pattern for low/medium volume dimensions and mutable workflow facts.
-- Use external table as the ADLS boundary, then load to transient STG_FLEET tables
-- for deterministic merges, DQ checks, joins, RI checks, and repeatable testing.
CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.CLIENTS_EXT
WITH LOCATION = @ADLS_STAGING_STAGE/domain=fleet_management/dataset=clients/
FILE_FORMAT = (TYPE = PARQUET)
AUTO_REFRESH = FALSE;

CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.CLIENTS AS
SELECT *
FROM STG_FLEET.CLIENTS_EXT;

-- External-first pattern for high-volume event stores.
-- Keep the partitioned event store external first; materialise repeated summaries into CONFORMED.
CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.TELEMATICS_DAILY_EXT
WITH LOCATION = @ADLS_STAGING_STAGE/domain=fleet_management/dataset=telematics_daily/
FILE_FORMAT = (TYPE = PARQUET)
AUTO_REFRESH = FALSE;

-- SCD Type 2 dimension merge by business key and source record hash.
-- Missing rows in authoritative full extracts are soft-deleted.
-- CONFORMED re-checks STAGING flags and DQ status before current-table merge.
UPDATE CONFORMED.DIM_CLIENT TGT
SET
  EFFECTIVE_TO = SRC.EFFECTIVE_AT,
  IS_CURRENT = FALSE,
  UPDATED_AT = CURRENT_TIMESTAMP()
FROM STG_FLEET.CLIENTS SRC
WHERE TGT.CLIENT_ID = SRC.CLIENT_ID
  AND TGT.IS_CURRENT = TRUE
  AND SRC._IS_LATEST_FOR_BUSINESS_KEY = TRUE
  AND SRC._LATEST_RESOLUTION_STATUS = 'resolved'
  AND SRC._IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(SRC._DQ_STATUS, 'passed') = 'passed'
  AND SRC._DELTA_ACTION <> 'DELETE'
  AND TGT.SOURCE_RECORD_HASH <> SRC._RECORD_HASH;

INSERT INTO CONFORMED.DIM_CLIENT (
  CLIENT_ID,
  ABN,
  CLIENT_NAME,
  INDUSTRY_SEGMENT,
  EMAIL_DOMAIN,
  ADDRESS_LINE_1,
  SUBURB,
  STATE,
  POSTCODE,
  COUNTRY,
  HEADQUARTERS_STATE,
  FLEET_SIZE_BAND,
  CONTRACT_START_DATE,
  CLIENT_STATUS,
  BUSINESS_KEY,
  EFFECTIVE_FROM,
  EFFECTIVE_TO,
  IS_CURRENT,
  DELETED_FLAG,
  SOURCE_EFFECTIVE_AT,
  SOURCE_UPDATED_AT,
  SOURCE_RECORD_HASH,
  CREATED_AT,
  UPDATED_AT
)
SELECT
  SRC.CLIENT_ID,
  SRC.ABN,
  SRC.CLIENT_NAME,
  SRC.INDUSTRY_SEGMENT,
  SRC.EMAIL_DOMAIN,
  SRC.ADDRESS_LINE_1,
  SRC.SUBURB,
  SRC.STATE,
  SRC.POSTCODE,
  SRC.COUNTRY,
  SRC.HEADQUARTERS_STATE,
  SRC.FLEET_SIZE_BAND,
  SRC.CONTRACT_START_DATE,
  SRC.CLIENT_STATUS,
  SRC.CLIENT_ID AS BUSINESS_KEY,
  SRC.EFFECTIVE_AT AS EFFECTIVE_FROM,
  '9999-12-31'::TIMESTAMP_NTZ AS EFFECTIVE_TO,
  TRUE AS IS_CURRENT,
  FALSE AS DELETED_FLAG,
  SRC.EFFECTIVE_AT AS SOURCE_EFFECTIVE_AT,
  SRC.UPDATED_AT AS SOURCE_UPDATED_AT,
  SRC._RECORD_HASH AS SOURCE_RECORD_HASH,
  CURRENT_TIMESTAMP() AS CREATED_AT,
  CURRENT_TIMESTAMP() AS UPDATED_AT
FROM STG_FLEET.CLIENTS SRC
LEFT JOIN CONFORMED.DIM_CLIENT TGT
  ON TGT.CLIENT_ID = SRC.CLIENT_ID
 AND TGT.IS_CURRENT = TRUE
WHERE SRC._IS_LATEST_FOR_BUSINESS_KEY = TRUE
  AND SRC._LATEST_RESOLUTION_STATUS = 'resolved'
  AND SRC._IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(SRC._DQ_STATUS, 'passed') = 'passed'
  AND SRC._DELTA_ACTION <> 'DELETE'
  AND (TGT.CLIENT_ID IS NULL OR TGT.SOURCE_RECORD_HASH <> SRC._RECORD_HASH);

UPDATE CONFORMED.DIM_CLIENT TGT
SET
  EFFECTIVE_TO = :batch_timestamp,
  IS_CURRENT = FALSE,
  DELETED_FLAG = TRUE,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TGT.IS_CURRENT = TRUE
  AND NOT EXISTS (
    SELECT 1
    FROM STG_FLEET.CLIENTS SRC
    WHERE SRC.CLIENT_ID = TGT.CLIENT_ID
      AND SRC._LOAD_TYPE = 'full'
  )
  AND EXISTS (
    SELECT 1
    FROM STG_FLEET.CLIENTS SRC
    WHERE SRC._LOAD_TYPE = 'full'
  );

-- Append-only event merge by event id. Missing events are never expired.
MERGE INTO CONFORMED.FACT_TELEMATICS_DAILY_SUMMARY TGT
USING (
  SELECT *
  FROM STG_FLEET.TELEMATICS_DAILY
  WHERE _IS_EXACT_DUPLICATE = FALSE
    AND COALESCE(_DQ_STATUS, 'passed') = 'passed'
) SRC
ON TGT.TELEMATICS_EVENT_ID = SRC.TELEMATICS_EVENT_ID
WHEN NOT MATCHED THEN INSERT (
  TELEMATICS_EVENT_ID,
  VEHICLE_ID,
  CLIENT_ID,
  EVENT_DATE,
  PROVIDER_NAME,
  DISTANCE_KM,
  IDLE_MINUTES,
  HARSH_EVENTS_COUNT,
  GPS_FIX_RATE_PCT,
  EVENT_BUSINESS_KEY,
  SOURCE_RECORD_HASH
) VALUES (
  SRC.TELEMATICS_EVENT_ID,
  SRC.VEHICLE_ID,
  SRC.CLIENT_ID,
  SRC.EVENT_DATE,
  SRC.PROVIDER_NAME,
  SRC.DISTANCE_KM,
  SRC.IDLE_MINUTES,
  SRC.HARSH_EVENTS_COUNT,
  SRC.GPS_FIX_RATE_PCT,
  SRC.TELEMATICS_EVENT_ID,
  SRC._RECORD_HASH
);

-- Version history insert/merge for mutable facts.
MERGE INTO CONFORMED.HIST_LEASE_CONTRACT_VERSION TGT
USING (
  SELECT *
  FROM STG_FLEET.LEASING_CONTRACTS
  WHERE _IS_EXACT_DUPLICATE = FALSE
    AND COALESCE(_DQ_STATUS, 'passed') = 'passed'
) SRC
ON TGT.EVENT_BUSINESS_KEY = SRC.LEASE_ID
AND TGT.SOURCE_UPDATED_AT = SRC.UPDATED_AT
AND TGT.SOURCE_RECORD_HASH = SRC._RECORD_HASH
WHEN NOT MATCHED THEN INSERT (
  LEASE_ID,
  VEHICLE_ID,
  CLIENT_ID,
  LEASE_PRODUCT,
  TERM_MONTHS,
  MONTHLY_RENTAL_AMOUNT,
  MANAGEMENT_FEE_AMOUNT,
  INCLUDED_SERVICES,
  RESIDUAL_VALUE_AMOUNT,
  LEASE_STATUS,
  EVENT_BUSINESS_KEY,
  SOURCE_UPDATED_AT,
  SOURCE_RECORD_HASH,
  DELTA_ACTION
) VALUES (
  SRC.LEASE_ID,
  SRC.VEHICLE_ID,
  SRC.CLIENT_ID,
  SRC.LEASE_PRODUCT,
  SRC.TERM_MONTHS,
  SRC.MONTHLY_RENTAL_AMOUNT,
  SRC.MANAGEMENT_FEE_AMOUNT,
  SRC.INCLUDED_SERVICES,
  SRC.RESIDUAL_VALUE_AMOUNT,
  SRC.LEASE_STATUS,
  SRC.LEASE_ID,
  SRC.UPDATED_AT,
  SRC._RECORD_HASH,
  SRC._DELTA_ACTION
);

-- Referential integrity check example: staged vehicles must resolve to a current client.
-- Rows returned by this query must be quarantined and excluded from current CONFORMED merges.
SELECT SRC.*
FROM STG_FLEET.VEHICLES SRC
LEFT JOIN CONFORMED.DIM_CLIENT PARENT
  ON PARENT.CLIENT_ID = SRC.CLIENT_ID
 AND PARENT.IS_CURRENT = TRUE
WHERE SRC.CLIENT_ID IS NOT NULL
  AND PARENT.CLIENT_ID IS NULL;

-- Event summary rebuild by batch_date. Use SQL first; use Snowpark only if this logic grows.
DELETE FROM CONFORMED.FACT_DRIVER_APP_DAILY_SUMMARY
WHERE BATCH_DATE = :batch_date;

INSERT INTO CONFORMED.FACT_DRIVER_APP_DAILY_SUMMARY (
  CLIENT_ID,
  VEHICLE_ID,
  EVENT_DATE,
  EVENT_COUNT,
  BATCH_DATE
)
SELECT
  CLIENT_ID,
  VEHICLE_ID,
  CAST(EVENT_DATETIME AS DATE) AS EVENT_DATE,
  COUNT(*) AS EVENT_COUNT,
  :batch_date AS BATCH_DATE
FROM STG_FLEET.DRIVER_APP_EVENTS
WHERE _BATCH_DATE = :batch_date
  AND _IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(_DQ_STATUS, 'passed') = 'passed'
GROUP BY CLIENT_ID, VEHICLE_ID, CAST(EVENT_DATETIME AS DATE);
