-- Element Fleet Customer 360 staging inputs for Snowflake.
--
-- Run after `element_fleet_snowflake_sit_setup.sql` has created
-- STG_FLEET.ADLS_STAGING_STAGE and STG_FLEET.PARQUET_FF.
--
-- Purpose:
--   Rebuild the STG_FLEET transient tables needed by
--   IDENTITY.BUILD_CUSTOMER360_IDENTITY from the current bb_datasets schemas.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FLEET_MVP_SIT_WH;
USE DATABASE FLEET_MVP_SIT;

CREATE SCHEMA IF NOT EXISTS STG_FLEET;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.LEASING_CONTRACTS_EXT (
  LEASE_ID VARCHAR AS (VALUE:lease_id::VARCHAR),
  VEHICLE_ID VARCHAR AS (VALUE:vehicle_id::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  LEASE_PRODUCT VARCHAR AS (VALUE:lease_product::VARCHAR),
  TERM_MONTHS NUMBER AS (TRY_TO_NUMBER(VALUE:term_months::VARCHAR)),
  MONTHLY_RENTAL_AMOUNT NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:monthly_rental_amount::VARCHAR, 18, 2)),
  MANAGEMENT_FEE_AMOUNT NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:management_fee_amount::VARCHAR, 18, 2)),
  INCLUDED_SERVICES VARCHAR AS (VALUE:included_services::VARCHAR),
  RESIDUAL_VALUE_AMOUNT NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:residual_value_amount::VARCHAR, 18, 2)),
  LEASE_STATUS VARCHAR AS (VALUE:lease_status::VARCHAR),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=leasing_contracts/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.FUEL_CARDS_EXT (
  FUEL_CARD_ID VARCHAR AS (VALUE:fuel_card_id::VARCHAR),
  VEHICLE_ID VARCHAR AS (VALUE:vehicle_id::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  PROVIDER_NAME VARCHAR AS (VALUE:provider_name::VARCHAR),
  CARD_STATUS VARCHAR AS (VALUE:card_status::VARCHAR),
  MONTHLY_LIMIT_AMOUNT NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:monthly_limit_amount::VARCHAR, 18, 2)),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=fuel_cards/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.FUEL_CARD_TRANSACTIONS_EXT (
  FUEL_TRANSACTION_ID VARCHAR AS (VALUE:fuel_transaction_id::VARCHAR),
  FUEL_CARD_ID VARCHAR AS (VALUE:fuel_card_id::VARCHAR),
  VEHICLE_ID VARCHAR AS (VALUE:vehicle_id::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  TRANSACTION_DATETIME TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:transaction_datetime::VARCHAR)),
  GROSS_AMOUNT NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:gross_amount::VARCHAR, 18, 2))
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=fuel_card_transactions/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.TELEMATICS_DAILY_EXT (
  TELEMATICS_EVENT_ID VARCHAR AS (VALUE:telematics_event_id::VARCHAR),
  VEHICLE_ID VARCHAR AS (VALUE:vehicle_id::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  TELEMATICS_DEVICE_ID VARCHAR AS (VALUE:telematics_device_id::VARCHAR),
  DEVICE_FIRMWARE_VERSION VARCHAR AS (VALUE:device_firmware_version::VARCHAR),
  EVENT_DATE DATE AS (TRY_TO_DATE(VALUE:event_date::VARCHAR)),
  PROVIDER_NAME VARCHAR AS (VALUE:provider_name::VARCHAR),
  DISTANCE_KM NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:distance_km::VARCHAR, 18, 2)),
  IDLE_MINUTES NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:idle_minutes::VARCHAR, 18, 2)),
  HARSH_EVENTS_COUNT NUMBER AS (TRY_TO_NUMBER(VALUE:harsh_events_count::VARCHAR)),
  GPS_FIX_RATE_PCT NUMBER(18, 4) AS (TRY_TO_NUMBER(VALUE:gps_fix_rate_pct::VARCHAR, 18, 4))
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=telematics_daily/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.MAINTENANCE_WORK_ORDERS_EXT (
  WORK_ORDER_ID VARCHAR AS (VALUE:work_order_id::VARCHAR),
  VEHICLE_ID VARCHAR AS (VALUE:vehicle_id::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  VENDOR_ID VARCHAR AS (VALUE:vendor_id::VARCHAR),
  OPENED_DATE DATE AS (TRY_TO_DATE(VALUE:opened_date::VARCHAR)),
  CLOSED_DATE DATE AS (TRY_TO_DATE(VALUE:closed_date::VARCHAR)),
  AUTHORISED_AMOUNT NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:authorised_amount::VARCHAR, 18, 2)),
  INVOICE_AMOUNT NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:invoice_amount::VARCHAR, 18, 2)),
  APPROVAL_STATUS VARCHAR AS (VALUE:approval_status::VARCHAR),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=maintenance_work_orders/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.INSURANCE_CLAIMS_EXT (
  CLAIM_ID VARCHAR AS (VALUE:claim_id::VARCHAR),
  CLAIM_NUMBER VARCHAR AS (VALUE:claim_number::VARCHAR),
  VEHICLE_ID VARCHAR AS (VALUE:vehicle_id::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  CLAIM_STATUS VARCHAR AS (VALUE:claim_status::VARCHAR),
  CLAIM_HANDLER_EMAIL_DOMAIN VARCHAR AS (VALUE:claim_handler_email_domain::VARCHAR),
  ESTIMATED_REPAIR_AMOUNT NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:estimated_repair_amount::VARCHAR, 18, 2)),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=insurance_claims/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.FINANCE_BILLING_INVOICES_EXT (
  INVOICE_ID VARCHAR AS (VALUE:invoice_id::VARCHAR),
  INVOICE_NUMBER VARCHAR AS (VALUE:invoice_number::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  BILLING_CONTACT_EMAIL_DOMAIN VARCHAR AS (VALUE:billing_contact_email_domain::VARCHAR),
  PURCHASE_ORDER_NUMBER VARCHAR AS (VALUE:purchase_order_number::VARCHAR),
  INVOICE_STATUS VARCHAR AS (VALUE:invoice_status::VARCHAR),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=finance_billing_invoices/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.CRM_CLIENT_PORTAL_EVENTS_EXT (
  PORTAL_EVENT_ID VARCHAR AS (VALUE:portal_event_id::VARCHAR),
  PORTAL_SESSION_ID VARCHAR AS (VALUE:portal_session_id::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  PORTAL_USER_ID VARCHAR AS (VALUE:portal_user_id::VARCHAR),
  CLIENT_CONTACT_EMAIL_DOMAIN VARCHAR AS (VALUE:client_contact_email_domain::VARCHAR),
  EVENT_DATETIME TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:event_datetime::VARCHAR)),
  SLA_BREACH_FLAG VARCHAR AS (VALUE:sla_breach_flag::VARCHAR),
  CASE_STATUS VARCHAR AS (VALUE:case_status::VARCHAR),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=crm_client_portal_events/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.EV_CHARGING_SESSIONS_EXT (
  CHARGING_SESSION_ID VARCHAR AS (VALUE:charging_session_id::VARCHAR),
  VEHICLE_ID VARCHAR AS (VALUE:vehicle_id::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  CHARGER_SERIAL_NUMBER VARCHAR AS (VALUE:charger_serial_number::VARCHAR),
  SESSION_START_DATETIME TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:session_start_datetime::VARCHAR)),
  ENERGY_KWH NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:energy_kwh::VARCHAR, 18, 2)),
  GROSS_AMOUNT NUMBER(18, 2) AS (TRY_TO_NUMBER(VALUE:gross_amount::VARCHAR, 18, 2)),
  REIMBURSEMENT_STATUS VARCHAR AS (VALUE:reimbursement_status::VARCHAR),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=ev_charging_sessions/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

ALTER EXTERNAL TABLE STG_FLEET.LEASING_CONTRACTS_EXT REFRESH;
ALTER EXTERNAL TABLE STG_FLEET.FUEL_CARDS_EXT REFRESH;
ALTER EXTERNAL TABLE STG_FLEET.FUEL_CARD_TRANSACTIONS_EXT REFRESH;
ALTER EXTERNAL TABLE STG_FLEET.TELEMATICS_DAILY_EXT REFRESH;
ALTER EXTERNAL TABLE STG_FLEET.MAINTENANCE_WORK_ORDERS_EXT REFRESH;
ALTER EXTERNAL TABLE STG_FLEET.INSURANCE_CLAIMS_EXT REFRESH;
ALTER EXTERNAL TABLE STG_FLEET.FINANCE_BILLING_INVOICES_EXT REFRESH;
ALTER EXTERNAL TABLE STG_FLEET.CRM_CLIENT_PORTAL_EVENTS_EXT REFRESH;
ALTER EXTERNAL TABLE STG_FLEET.EV_CHARGING_SESSIONS_EXT REFRESH;

CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.LEASING_CONTRACTS AS SELECT * FROM STG_FLEET.LEASING_CONTRACTS_EXT;
CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.FUEL_CARDS AS SELECT * FROM STG_FLEET.FUEL_CARDS_EXT;
CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.FUEL_CARD_TRANSACTIONS AS SELECT * FROM STG_FLEET.FUEL_CARD_TRANSACTIONS_EXT;
CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.TELEMATICS_DAILY AS SELECT * FROM STG_FLEET.TELEMATICS_DAILY_EXT;
CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.MAINTENANCE_WORK_ORDERS AS SELECT * FROM STG_FLEET.MAINTENANCE_WORK_ORDERS_EXT;
CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.INSURANCE_CLAIMS AS SELECT * FROM STG_FLEET.INSURANCE_CLAIMS_EXT;
CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.FINANCE_BILLING_INVOICES AS SELECT * FROM STG_FLEET.FINANCE_BILLING_INVOICES_EXT;
CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.CRM_CLIENT_PORTAL_EVENTS AS SELECT * FROM STG_FLEET.CRM_CLIENT_PORTAL_EVENTS_EXT;
CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.EV_CHARGING_SESSIONS AS SELECT * FROM STG_FLEET.EV_CHARGING_SESSIONS_EXT;
