-- Element Fleet Customer 360 identity-resolution solution.
--
-- Design source:
--   design/element_fleet_artefacts/element_fleet_customer360_identity_resolution_design_snowflake_first.md
--
-- Scope:
--   Snowflake-first Customer 360 identity foundation over the existing Element
--   Fleet conformed layer. This artifact creates standardised identity tables,
--   deterministic and fuzzy match candidates, golden entities, source xrefs,
--   relationship tables, a steward review queue, a Customer 360 mart, and an
--   AI-safe semantic view.
--
-- Delivery assumptions:
--   * CONFORMED.DIM_CLIENT and CONFORMED.DIM_VEHICLE are the minimum required
--     conformed sources.
--   * ABN, address, domain, VIN, registration plate, telematics device, claims,
--     invoice, portal, and EV charging inputs are exposed by the Element Fleet
--     bb_datasets source metadata and are consumed by this identity layer once
--     STG_FLEET and CONFORMED are rebuilt from the current source schema.
--   * No trusted driver master is assumed. Driver data remains linked through
--     vehicle/client relationships.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FLEET_MVP_SIT_WH;
USE DATABASE FLEET_MVP_SIT;

CREATE SCHEMA IF NOT EXISTS IDENTITY;
CREATE SCHEMA IF NOT EXISTS GOLDEN;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS SEMANTIC;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE TABLE IF NOT EXISTS IDENTITY.STD_CUSTOMER (
  SOURCE_SYSTEM_ID VARCHAR,
  SOURCE_CUSTOMER_ID VARCHAR,
  CUSTOMER_NAME VARCHAR,
  STD_CUSTOMER_NAME_RAW VARCHAR,
  STD_CUSTOMER_NAME VARCHAR,
  STD_ABN VARCHAR,
  STD_EMAIL_DOMAIN VARCHAR,
  STD_ADDRESS_LINE_1 VARCHAR,
  STD_SUBURB VARCHAR,
  STD_STATE VARCHAR,
  STD_POSTCODE VARCHAR,
  STD_COUNTRY VARCHAR,
  CUSTOMER_SEGMENT VARCHAR,
  CUSTOMER_STATUS VARCHAR,
  SOURCE_UPDATED_AT TIMESTAMP_NTZ,
  CREATED_RUN_ID VARCHAR,
  STANDARDISED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTITY.STD_VEHICLE (
  SOURCE_SYSTEM_ID VARCHAR,
  SOURCE_VEHICLE_ID VARCHAR,
  SOURCE_CUSTOMER_ID VARCHAR,
  STD_VIN VARCHAR,
  STD_REGISTRATION_PLATE VARCHAR,
  STD_TELEMATICS_DEVICE_ID VARCHAR,
  TELEMATICS_DEVICE_MODEL VARCHAR,
  TELEMATICS_INSTALL_DATE DATE,
  STATE_REGISTERED VARCHAR,
  ASSET_TYPE VARCHAR,
  MAKE VARCHAR,
  MODEL VARCHAR,
  MODEL_YEAR NUMBER,
  FUEL_TYPE VARCHAR,
  VEHICLE_STATUS VARCHAR,
  SOURCE_UPDATED_AT TIMESTAMP_NTZ,
  CREATED_RUN_ID VARCHAR,
  STANDARDISED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTITY.STD_ACCOUNT (
  SOURCE_SYSTEM_ID VARCHAR,
  SOURCE_ACCOUNT_ID VARCHAR,
  SOURCE_CUSTOMER_ID VARCHAR,
  STD_ACCOUNT_KEY VARCHAR,
  ACCOUNT_TYPE VARCHAR,
  ACCOUNT_STATUS VARCHAR,
  SOURCE_UPDATED_AT TIMESTAMP_NTZ,
  CREATED_RUN_ID VARCHAR,
  STANDARDISED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTITY.STD_FUEL_CARD (
  SOURCE_SYSTEM_ID VARCHAR,
  SOURCE_FUEL_CARD_ID VARCHAR,
  SOURCE_VEHICLE_ID VARCHAR,
  SOURCE_CUSTOMER_ID VARCHAR,
  HASHED_FUEL_CARD_NUMBER VARCHAR,
  CARD_STATUS VARCHAR,
  SOURCE_UPDATED_AT TIMESTAMP_NTZ,
  CREATED_RUN_ID VARCHAR,
  STANDARDISED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTITY.STD_DEVICE (
  SOURCE_SYSTEM_ID VARCHAR,
  SOURCE_DEVICE_ID VARCHAR,
  SOURCE_VEHICLE_ID VARCHAR,
  PROVIDER_NAME VARCHAR,
  STD_PROVIDER_DEVICE_ID VARCHAR,
  SOURCE_UPDATED_AT TIMESTAMP_NTZ,
  CREATED_RUN_ID VARCHAR,
  STANDARDISED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTITY.STD_SUPPLIER (
  SOURCE_SYSTEM_ID VARCHAR,
  SOURCE_SUPPLIER_ID VARCHAR,
  SUPPLIER_NAME VARCHAR,
  STD_SUPPLIER_NAME VARCHAR,
  STD_ABN VARCHAR,
  SUPPLIER_TYPE VARCHAR,
  STATE VARCHAR,
  SOURCE_UPDATED_AT TIMESTAMP_NTZ,
  CREATED_RUN_ID VARCHAR,
  STANDARDISED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTITY.CUSTOMER_MATCH_CANDIDATE (
  CANDIDATE_ID VARCHAR,
  ENTITY_TYPE VARCHAR,
  SOURCE_RECORD_A VARCHAR,
  SOURCE_RECORD_B VARCHAR,
  MATCH_SCORE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  AUTO_MATCH_FLAG BOOLEAN,
  REVIEW_REQUIRED_FLAG BOOLEAN,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTITY.VEHICLE_MATCH_CANDIDATE (
  CANDIDATE_ID VARCHAR,
  ENTITY_TYPE VARCHAR,
  SOURCE_RECORD_A VARCHAR,
  SOURCE_RECORD_B VARCHAR,
  MATCH_SCORE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  AUTO_MATCH_FLAG BOOLEAN,
  REVIEW_REQUIRED_FLAG BOOLEAN,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTITY.DEVICE_VEHICLE_MATCH_CANDIDATE (
  CANDIDATE_ID VARCHAR,
  ENTITY_TYPE VARCHAR,
  SOURCE_RECORD_A VARCHAR,
  SOURCE_RECORD_B VARCHAR,
  MATCH_SCORE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  AUTO_MATCH_FLAG BOOLEAN,
  REVIEW_REQUIRED_FLAG BOOLEAN,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTITY.ACCOUNT_CUSTOMER_MATCH_CANDIDATE (
  CANDIDATE_ID VARCHAR,
  ENTITY_TYPE VARCHAR,
  SOURCE_RECORD_A VARCHAR,
  SOURCE_RECORD_B VARCHAR,
  MATCH_SCORE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  AUTO_MATCH_FLAG BOOLEAN,
  REVIEW_REQUIRED_FLAG BOOLEAN,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.GOLDEN_CUSTOMER (
  GOLDEN_CUSTOMER_ID VARCHAR,
  CUSTOMER_NAME VARCHAR,
  CUSTOMER_SEGMENT VARCHAR,
  CUSTOMER_STATUS VARCHAR,
  PRIMARY_SOURCE_SYSTEM_ID VARCHAR,
  PRIMARY_SOURCE_CUSTOMER_ID VARCHAR,
  IDENTITY_RESOLUTION_CONFIDENCE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  SURVIVORSHIP_RULE_VERSION VARCHAR,
  ATTRIBUTE_SOURCE_SYSTEM VARCHAR,
  ATTRIBUTE_SOURCE_RECORD_ID VARCHAR,
  ATTRIBUTE_LAST_UPDATED_AT TIMESTAMP_NTZ,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.GOLDEN_VEHICLE (
  GOLDEN_VEHICLE_ID VARCHAR,
  GOLDEN_CUSTOMER_ID VARCHAR,
  VEHICLE_ID VARCHAR,
  VIN VARCHAR,
  REGISTRATION_PLATE VARCHAR,
  STATE_REGISTERED VARCHAR,
  ASSET_TYPE VARCHAR,
  MAKE VARCHAR,
  MODEL VARCHAR,
  MODEL_YEAR NUMBER,
  FUEL_TYPE VARCHAR,
  VEHICLE_STATUS VARCHAR,
  IDENTITY_RESOLUTION_CONFIDENCE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  SURVIVORSHIP_RULE_VERSION VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.GOLDEN_ACCOUNT (
  GOLDEN_ACCOUNT_ID VARCHAR,
  GOLDEN_CUSTOMER_ID VARCHAR,
  ACCOUNT_TYPE VARCHAR,
  ACCOUNT_STATUS VARCHAR,
  IDENTITY_RESOLUTION_CONFIDENCE NUMBER(10, 6),
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.GOLDEN_SUPPLIER (
  GOLDEN_SUPPLIER_ID VARCHAR,
  SUPPLIER_NAME VARCHAR,
  SUPPLIER_TYPE VARCHAR,
  STATE VARCHAR,
  IDENTITY_RESOLUTION_CONFIDENCE NUMBER(10, 6),
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.GOLDEN_FUEL_CARD (
  GOLDEN_FUEL_CARD_ID VARCHAR,
  GOLDEN_VEHICLE_ID VARCHAR,
  GOLDEN_CUSTOMER_ID VARCHAR,
  CARD_STATUS VARCHAR,
  IDENTITY_RESOLUTION_CONFIDENCE NUMBER(10, 6),
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.GOLDEN_DRIVER_PLACEHOLDER (
  GOLDEN_DRIVER_PLACEHOLDER_ID VARCHAR,
  GOLDEN_CUSTOMER_ID VARCHAR,
  GOLDEN_VEHICLE_ID VARCHAR,
  SOURCE_CONTEXT VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.XREF_CUSTOMER_SOURCE (
  GOLDEN_CUSTOMER_ID VARCHAR,
  SOURCE_SYSTEM VARCHAR,
  SOURCE_CUSTOMER_ID VARCHAR,
  MATCH_CONFIDENCE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.XREF_VEHICLE_SOURCE (
  GOLDEN_VEHICLE_ID VARCHAR,
  GOLDEN_CUSTOMER_ID VARCHAR,
  SOURCE_SYSTEM VARCHAR,
  SOURCE_VEHICLE_ID VARCHAR,
  MATCH_CONFIDENCE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.XREF_ACCOUNT_SOURCE (
  GOLDEN_ACCOUNT_ID VARCHAR,
  GOLDEN_CUSTOMER_ID VARCHAR,
  SOURCE_SYSTEM VARCHAR,
  SOURCE_ACCOUNT_ID VARCHAR,
  MATCH_CONFIDENCE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.XREF_FUEL_CARD_SOURCE (
  GOLDEN_FUEL_CARD_ID VARCHAR,
  GOLDEN_VEHICLE_ID VARCHAR,
  GOLDEN_CUSTOMER_ID VARCHAR,
  SOURCE_SYSTEM VARCHAR,
  SOURCE_FUEL_CARD_ID VARCHAR,
  MATCH_CONFIDENCE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.XREF_DEVICE_SOURCE (
  GOLDEN_DEVICE_ID VARCHAR,
  GOLDEN_VEHICLE_ID VARCHAR,
  GOLDEN_CUSTOMER_ID VARCHAR,
  SOURCE_SYSTEM VARCHAR,
  SOURCE_DEVICE_ID VARCHAR,
  MATCH_CONFIDENCE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.XREF_SUPPLIER_SOURCE (
  GOLDEN_SUPPLIER_ID VARCHAR,
  SOURCE_SYSTEM VARCHAR,
  SOURCE_SUPPLIER_ID VARCHAR,
  MATCH_CONFIDENCE NUMBER(10, 6),
  MATCH_METHOD VARCHAR,
  MATCH_REASON_CODE VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.REL_CUSTOMER_VEHICLE (
  GOLDEN_CUSTOMER_ID VARCHAR,
  GOLDEN_VEHICLE_ID VARCHAR,
  RELATIONSHIP_STATUS VARCHAR,
  RELATIONSHIP_START_DATE DATE,
  RELATIONSHIP_END_DATE DATE,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.REL_CUSTOMER_CONTRACT (
  GOLDEN_CUSTOMER_ID VARCHAR,
  CONTRACT_ID VARCHAR,
  RELATIONSHIP_STATUS VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.REL_VEHICLE_FUEL_CARD (
  GOLDEN_VEHICLE_ID VARCHAR,
  GOLDEN_FUEL_CARD_ID VARCHAR,
  RELATIONSHIP_STATUS VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.REL_VEHICLE_TELEMATICS_DEVICE (
  GOLDEN_VEHICLE_ID VARCHAR,
  GOLDEN_DEVICE_ID VARCHAR,
  PROVIDER_NAME VARCHAR,
  RELATIONSHIP_STATUS VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.REL_CUSTOMER_PORTAL_ACCOUNT (
  GOLDEN_CUSTOMER_ID VARCHAR,
  PORTAL_ACCOUNT_ID VARCHAR,
  RELATIONSHIP_STATUS VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLDEN.REL_VEHICLE_DRIVER_APP_PROFILE (
  GOLDEN_VEHICLE_ID VARCHAR,
  DRIVER_APP_PROFILE_ID VARCHAR,
  RELATIONSHIP_STATUS VARCHAR,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.IDENTITY_REVIEW_QUEUE (
  REVIEW_CASE_ID VARCHAR,
  ENTITY_TYPE VARCHAR,
  CANDIDATE_RECORD_A VARCHAR,
  CANDIDATE_RECORD_B VARCHAR,
  MATCH_SCORE NUMBER(10, 6),
  MATCH_REASON VARCHAR,
  CONFLICTING_ATTRIBUTES VARCHAR,
  RECOMMENDED_ACTION VARCHAR,
  REVIEW_STATUS VARCHAR,
  REVIEWED_BY VARCHAR,
  REVIEWED_AT TIMESTAMP_NTZ,
  CREATED_RUN_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOLD.CUSTOMER_360_MART (
  GOLDEN_CUSTOMER_ID VARCHAR,
  CUSTOMER_NAME VARCHAR,
  CUSTOMER_SEGMENT VARCHAR,
  ACTIVE_VEHICLE_COUNT NUMBER,
  ACTIVE_CONTRACT_COUNT NUMBER,
  MONTHLY_TCO NUMBER(18, 2),
  MAINTENANCE_COST_90D NUMBER(18, 2),
  FUEL_COST_90D NUMBER(18, 2),
  EV_CHARGING_COST_90D NUMBER(18, 2),
  OPEN_CLAIM_COUNT NUMBER,
  PORTAL_ACTIVITY_SCORE NUMBER(18, 6),
  SERVICE_RISK_SCORE NUMBER(18, 6),
  FLEET_GROWTH_OPPORTUNITY_SCORE NUMBER(18, 6),
  DATA_QUALITY_STATUS VARCHAR,
  IDENTITY_RESOLUTION_CONFIDENCE NUMBER(10, 6),
  CREATED_RUN_ID VARCHAR,
  BUILT_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE PROCEDURE IDENTITY.BUILD_CUSTOMER360_IDENTITY(BATCH_DATE DATE, RUN_ID VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
  CREATE OR REPLACE TABLE IDENTITY.STD_CUSTOMER AS
  SELECT
    'CONFORMED' AS SOURCE_SYSTEM_ID,
    CLIENT_ID AS SOURCE_CUSTOMER_ID,
    CLIENT_NAME AS CUSTOMER_NAME,
    UPPER(REGEXP_REPLACE(COALESCE(CLIENT_NAME, ''), '[^A-Z0-9 ]', '')) AS STD_CUSTOMER_NAME_RAW,
    TRIM(REGEXP_REPLACE(
      REGEXP_REPLACE(UPPER(COALESCE(CLIENT_NAME, '')), '\\bPTY LTD\\b|\\bPROPRIETARY LIMITED\\b|\\bLIMITED\\b|\\bLTD\\b|\\bINC\\b|\\bCORP\\b', ''),
      '\\s+',
      ' '
    )) AS STD_CUSTOMER_NAME,
    REGEXP_REPLACE(COALESCE(ABN, ''), '[^0-9]', '') AS STD_ABN,
    LOWER(TRIM(EMAIL_DOMAIN)) AS STD_EMAIL_DOMAIN,
    TRIM(REGEXP_REPLACE(UPPER(COALESCE(ADDRESS_LINE_1, '')), '\\s+', ' ')) AS STD_ADDRESS_LINE_1,
    TRIM(REGEXP_REPLACE(UPPER(COALESCE(SUBURB, '')), '\\s+', ' ')) AS STD_SUBURB,
    UPPER(TRIM(COALESCE(STATE, HEADQUARTERS_STATE))) AS STD_STATE,
    REGEXP_REPLACE(COALESCE(POSTCODE, ''), '[^0-9]', '') AS STD_POSTCODE,
    UPPER(TRIM(COALESCE(COUNTRY, 'AU'))) AS STD_COUNTRY,
    COALESCE(INDUSTRY_SEGMENT, FLEET_SIZE_BAND) AS CUSTOMER_SEGMENT,
    CLIENT_STATUS AS CUSTOMER_STATUS,
    SOURCE_UPDATED_AT,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS STANDARDISED_AT
  FROM CONFORMED.DIM_CLIENT
  WHERE IS_CURRENT = TRUE
    AND COALESCE(DELETED_FLAG, FALSE) = FALSE;

  CREATE OR REPLACE TABLE IDENTITY.STD_VEHICLE AS
  SELECT
    'CONFORMED' AS SOURCE_SYSTEM_ID,
    VEHICLE_ID AS SOURCE_VEHICLE_ID,
    CLIENT_ID AS SOURCE_CUSTOMER_ID,
    UPPER(REGEXP_REPLACE(COALESCE(VIN, ''), '[^A-Z0-9]', '')) AS STD_VIN,
    UPPER(REGEXP_REPLACE(COALESCE(REGISTRATION_PLATE, ''), '[^A-Z0-9]', '')) AS STD_REGISTRATION_PLATE,
    UPPER(TRIM(COALESCE(TELEMATICS_DEVICE_ID, ''))) AS STD_TELEMATICS_DEVICE_ID,
    TELEMATICS_DEVICE_MODEL,
    TELEMATICS_INSTALL_DATE,
    STATE_REGISTERED,
    ASSET_TYPE,
    MAKE,
    MODEL,
    MODEL_YEAR,
    FUEL_TYPE,
    VEHICLE_STATUS,
    SOURCE_UPDATED_AT,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS STANDARDISED_AT
  FROM CONFORMED.DIM_VEHICLE
  WHERE IS_CURRENT = TRUE
    AND COALESCE(DELETED_FLAG, FALSE) = FALSE;

  CREATE OR REPLACE TABLE IDENTITY.STD_ACCOUNT AS
  SELECT
    'STG_FLEET.FINANCE_BILLING_INVOICES' AS SOURCE_SYSTEM_ID,
    INVOICE_ID AS SOURCE_ACCOUNT_ID,
    CLIENT_ID AS SOURCE_CUSTOMER_ID,
    UPPER(TRIM(COALESCE(PURCHASE_ORDER_NUMBER, INVOICE_NUMBER, INVOICE_ID))) AS STD_ACCOUNT_KEY,
    'billing_invoice' AS ACCOUNT_TYPE,
    INVOICE_STATUS AS ACCOUNT_STATUS,
    UPDATED_AT AS SOURCE_UPDATED_AT,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS STANDARDISED_AT
  FROM STG_FLEET.FINANCE_BILLING_INVOICES
  WHERE _IS_LATEST_FOR_BUSINESS_KEY = TRUE
    AND _LATEST_RESOLUTION_STATUS = 'resolved'
    AND _IS_EXACT_DUPLICATE = FALSE
    AND COALESCE(_DQ_STATUS, 'passed') = 'passed';

  CREATE OR REPLACE TABLE IDENTITY.STD_FUEL_CARD AS
  SELECT
    'STG_FLEET.FUEL_CARDS' AS SOURCE_SYSTEM_ID,
    FUEL_CARD_ID AS SOURCE_FUEL_CARD_ID,
    VEHICLE_ID AS SOURCE_VEHICLE_ID,
    CLIENT_ID AS SOURCE_CUSTOMER_ID,
    SHA2(FUEL_CARD_ID, 256) AS HASHED_FUEL_CARD_NUMBER,
    CARD_STATUS,
    UPDATED_AT AS SOURCE_UPDATED_AT,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS STANDARDISED_AT
  FROM STG_FLEET.FUEL_CARDS
  WHERE _IS_LATEST_FOR_BUSINESS_KEY = TRUE
    AND _LATEST_RESOLUTION_STATUS = 'resolved'
    AND _IS_EXACT_DUPLICATE = FALSE
    AND COALESCE(_DQ_STATUS, 'passed') = 'passed';

  CREATE OR REPLACE TABLE IDENTITY.STD_DEVICE AS
  SELECT DISTINCT
    'CONFORMED.DIM_VEHICLE' AS SOURCE_SYSTEM_ID,
    STD_TELEMATICS_DEVICE_ID AS SOURCE_DEVICE_ID,
    SOURCE_VEHICLE_ID,
    NULL::VARCHAR AS PROVIDER_NAME,
    STD_TELEMATICS_DEVICE_ID AS STD_PROVIDER_DEVICE_ID,
    SOURCE_UPDATED_AT,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS STANDARDISED_AT
  FROM IDENTITY.STD_VEHICLE
  WHERE STD_TELEMATICS_DEVICE_ID IS NOT NULL
    AND STD_TELEMATICS_DEVICE_ID <> ''
  UNION
  SELECT DISTINCT
    'STG_FLEET.TELEMATICS_DAILY' AS SOURCE_SYSTEM_ID,
    UPPER(TRIM(TELEMATICS_DEVICE_ID)) AS SOURCE_DEVICE_ID,
    VEHICLE_ID AS SOURCE_VEHICLE_ID,
    PROVIDER_NAME,
    CONCAT(UPPER(TRIM(PROVIDER_NAME)), ':', UPPER(TRIM(TELEMATICS_DEVICE_ID))) AS STD_PROVIDER_DEVICE_ID,
    NULL::TIMESTAMP_NTZ AS SOURCE_UPDATED_AT,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS STANDARDISED_AT
  FROM STG_FLEET.TELEMATICS_DAILY
  WHERE TELEMATICS_DEVICE_ID IS NOT NULL
    AND TELEMATICS_DEVICE_ID <> '';

  CREATE OR REPLACE TABLE IDENTITY.CUSTOMER_MATCH_CANDIDATE AS
  WITH deterministic AS (
    SELECT
      SHA2(CONCAT_WS('|', 'customer', C1.SOURCE_RECORD_A, C1.SOURCE_RECORD_B, C1.MATCH_METHOD), 256) AS CANDIDATE_ID,
      'customer' AS ENTITY_TYPE,
      C1.SOURCE_RECORD_A,
      C1.SOURCE_RECORD_B,
      1.000000::NUMBER(10, 6) AS MATCH_SCORE,
      C1.MATCH_METHOD,
      C1.MATCH_REASON_CODE,
      TRUE AS AUTO_MATCH_FLAG,
      FALSE AS REVIEW_REQUIRED_FLAG,
      :RUN_ID AS CREATED_RUN_ID,
      CURRENT_TIMESTAMP() AS CREATED_AT
    FROM (
      SELECT
        A.SOURCE_CUSTOMER_ID AS SOURCE_RECORD_A,
        B.SOURCE_CUSTOMER_ID AS SOURCE_RECORD_B,
        'deterministic_source_customer_id' AS MATCH_METHOD,
        'same_source_customer_id' AS MATCH_REASON_CODE
      FROM IDENTITY.STD_CUSTOMER A
      JOIN IDENTITY.STD_CUSTOMER B
        ON A.SOURCE_CUSTOMER_ID = B.SOURCE_CUSTOMER_ID
       AND A.SOURCE_SYSTEM_ID <= B.SOURCE_SYSTEM_ID
      WHERE A.SOURCE_CUSTOMER_ID IS NOT NULL
      UNION ALL
      SELECT
        A.SOURCE_CUSTOMER_ID AS SOURCE_RECORD_A,
        B.SOURCE_CUSTOMER_ID AS SOURCE_RECORD_B,
        'deterministic_abn' AS MATCH_METHOD,
        'same_abn' AS MATCH_REASON_CODE
      FROM IDENTITY.STD_CUSTOMER A
      JOIN IDENTITY.STD_CUSTOMER B
        ON A.STD_ABN = B.STD_ABN
       AND A.SOURCE_CUSTOMER_ID < B.SOURCE_CUSTOMER_ID
      WHERE A.STD_ABN IS NOT NULL
        AND LENGTH(A.STD_ABN) > 0
    ) C1
  ),
  fuzzy_scored AS (
    SELECT
      SHA2(CONCAT_WS('|', 'customer', A.SOURCE_CUSTOMER_ID, B.SOURCE_CUSTOMER_ID, 'fuzzy_name_state'), 256) AS CANDIDATE_ID,
      'customer' AS ENTITY_TYPE,
      A.SOURCE_CUSTOMER_ID AS SOURCE_RECORD_A,
      B.SOURCE_CUSTOMER_ID AS SOURCE_RECORD_B,
      (
        0.80 * (
          1 - (
            EDITDISTANCE(A.STD_CUSTOMER_NAME, B.STD_CUSTOMER_NAME)
            / NULLIF(GREATEST(LENGTH(A.STD_CUSTOMER_NAME), LENGTH(B.STD_CUSTOMER_NAME)), 0)
          )
        )
        + 0.20 * IFF(COALESCE(A.STD_POSTCODE, '') = COALESCE(B.STD_POSTCODE, ''), 1, 0)
      )::NUMBER(10, 6) AS MATCH_SCORE,
      'fuzzy_name_state' AS MATCH_METHOD,
      'name_address_domain_block' AS MATCH_REASON_CODE
    FROM IDENTITY.STD_CUSTOMER A
    JOIN IDENTITY.STD_CUSTOMER B
      ON SUBSTR(A.STD_CUSTOMER_NAME, 1, 5) = SUBSTR(B.STD_CUSTOMER_NAME, 1, 5)
     AND (
       COALESCE(A.STD_POSTCODE, '') = COALESCE(B.STD_POSTCODE, '')
       OR COALESCE(A.STD_EMAIL_DOMAIN, '') = COALESCE(B.STD_EMAIL_DOMAIN, '')
     )
     AND A.SOURCE_CUSTOMER_ID < B.SOURCE_CUSTOMER_ID
    WHERE LENGTH(A.STD_CUSTOMER_NAME) > 0
      AND LENGTH(B.STD_CUSTOMER_NAME) > 0
  ),
  fuzzy AS (
    SELECT
      CANDIDATE_ID,
      ENTITY_TYPE,
      SOURCE_RECORD_A,
      SOURCE_RECORD_B,
      MATCH_SCORE,
      MATCH_METHOD,
      MATCH_REASON_CODE,
      MATCH_SCORE >= 0.95 AS AUTO_MATCH_FLAG,
      MATCH_SCORE >= 0.70 AND MATCH_SCORE < 0.95 AS REVIEW_REQUIRED_FLAG,
      :RUN_ID AS CREATED_RUN_ID,
      CURRENT_TIMESTAMP() AS CREATED_AT
    FROM fuzzy_scored
  )
  SELECT * FROM deterministic
  UNION ALL
  SELECT * FROM fuzzy
  WHERE MATCH_SCORE >= 0.70;

  CREATE OR REPLACE TABLE IDENTITY.VEHICLE_MATCH_CANDIDATE AS
  SELECT
    SHA2(CONCAT_WS('|', 'vehicle', SOURCE_VEHICLE_ID, 'deterministic_vehicle_id'), 256) AS CANDIDATE_ID,
    'vehicle' AS ENTITY_TYPE,
    SOURCE_VEHICLE_ID AS SOURCE_RECORD_A,
    SOURCE_VEHICLE_ID AS SOURCE_RECORD_B,
    1.000000::NUMBER(10, 6) AS MATCH_SCORE,
    IFF(STD_VIN IS NOT NULL AND STD_VIN <> '', 'deterministic_vin', 'deterministic_vehicle_id') AS MATCH_METHOD,
    IFF(STD_VIN IS NOT NULL AND STD_VIN <> '', 'same_vin', 'same_source_vehicle_id') AS MATCH_REASON_CODE,
    TRUE AS AUTO_MATCH_FLAG,
    FALSE AS REVIEW_REQUIRED_FLAG,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM IDENTITY.STD_VEHICLE
  WHERE SOURCE_VEHICLE_ID IS NOT NULL;

  CREATE OR REPLACE TABLE IDENTITY.DEVICE_VEHICLE_MATCH_CANDIDATE AS
  SELECT
    SHA2(CONCAT_WS('|', 'device_vehicle', SOURCE_DEVICE_ID, SOURCE_VEHICLE_ID), 256) AS CANDIDATE_ID,
    'device_vehicle' AS ENTITY_TYPE,
    SOURCE_DEVICE_ID AS SOURCE_RECORD_A,
    SOURCE_VEHICLE_ID AS SOURCE_RECORD_B,
    1.000000::NUMBER(10, 6) AS MATCH_SCORE,
    'deterministic_provider_device_id' AS MATCH_METHOD,
    'same_device_vehicle_assignment' AS MATCH_REASON_CODE,
    TRUE AS AUTO_MATCH_FLAG,
    FALSE AS REVIEW_REQUIRED_FLAG,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM IDENTITY.STD_DEVICE
  WHERE SOURCE_DEVICE_ID IS NOT NULL
    AND SOURCE_VEHICLE_ID IS NOT NULL;

  CREATE OR REPLACE TABLE IDENTITY.ACCOUNT_CUSTOMER_MATCH_CANDIDATE AS
  SELECT
    SHA2(CONCAT_WS('|', 'account_customer', SOURCE_ACCOUNT_ID, SOURCE_CUSTOMER_ID), 256) AS CANDIDATE_ID,
    'account_customer' AS ENTITY_TYPE,
    SOURCE_ACCOUNT_ID AS SOURCE_RECORD_A,
    SOURCE_CUSTOMER_ID AS SOURCE_RECORD_B,
    1.000000::NUMBER(10, 6) AS MATCH_SCORE,
    'deterministic_invoice_customer_id' AS MATCH_METHOD,
    'same_invoice_customer_relationship' AS MATCH_REASON_CODE,
    TRUE AS AUTO_MATCH_FLAG,
    FALSE AS REVIEW_REQUIRED_FLAG,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM IDENTITY.STD_ACCOUNT
  WHERE SOURCE_ACCOUNT_ID IS NOT NULL
    AND SOURCE_CUSTOMER_ID IS NOT NULL;

  CREATE OR REPLACE TABLE GOLDEN.GOLDEN_CUSTOMER AS
  SELECT
    CONCAT('GCUST_', SUBSTR(SHA2(SOURCE_CUSTOMER_ID, 256), 1, 16)) AS GOLDEN_CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    CUSTOMER_STATUS,
    SOURCE_SYSTEM_ID AS PRIMARY_SOURCE_SYSTEM_ID,
    SOURCE_CUSTOMER_ID AS PRIMARY_SOURCE_CUSTOMER_ID,
    1.000000::NUMBER(10, 6) AS IDENTITY_RESOLUTION_CONFIDENCE,
    'deterministic_source_customer_id' AS MATCH_METHOD,
    'customer_survivorship_v0.1' AS SURVIVORSHIP_RULE_VERSION,
    SOURCE_SYSTEM_ID AS ATTRIBUTE_SOURCE_SYSTEM,
    SOURCE_CUSTOMER_ID AS ATTRIBUTE_SOURCE_RECORD_ID,
    SOURCE_UPDATED_AT AS ATTRIBUTE_LAST_UPDATED_AT,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
  FROM IDENTITY.STD_CUSTOMER;

  CREATE OR REPLACE TABLE GOLDEN.XREF_CUSTOMER_SOURCE AS
  SELECT
    GOLDEN_CUSTOMER_ID,
    PRIMARY_SOURCE_SYSTEM_ID AS SOURCE_SYSTEM,
    PRIMARY_SOURCE_CUSTOMER_ID AS SOURCE_CUSTOMER_ID,
    IDENTITY_RESOLUTION_CONFIDENCE AS MATCH_CONFIDENCE,
    MATCH_METHOD,
    'same_source_customer_id' AS MATCH_REASON_CODE,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM GOLDEN.GOLDEN_CUSTOMER;

  CREATE OR REPLACE TABLE GOLDEN.GOLDEN_VEHICLE AS
  SELECT
    CONCAT('GVEH_', SUBSTR(SHA2(V.SOURCE_VEHICLE_ID, 256), 1, 16)) AS GOLDEN_VEHICLE_ID,
    C.GOLDEN_CUSTOMER_ID,
    V.SOURCE_VEHICLE_ID AS VEHICLE_ID,
    V.STD_VIN AS VIN,
    V.STD_REGISTRATION_PLATE AS REGISTRATION_PLATE,
    V.STATE_REGISTERED,
    V.ASSET_TYPE,
    V.MAKE,
    V.MODEL,
    V.MODEL_YEAR,
    V.FUEL_TYPE,
    V.VEHICLE_STATUS,
    1.000000::NUMBER(10, 6) AS IDENTITY_RESOLUTION_CONFIDENCE,
    'deterministic_vehicle_id' AS MATCH_METHOD,
    'vehicle_survivorship_v0.1' AS SURVIVORSHIP_RULE_VERSION,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
  FROM IDENTITY.STD_VEHICLE V
  LEFT JOIN GOLDEN.GOLDEN_CUSTOMER C
    ON C.PRIMARY_SOURCE_CUSTOMER_ID = V.SOURCE_CUSTOMER_ID;

  CREATE OR REPLACE TABLE GOLDEN.XREF_VEHICLE_SOURCE AS
  SELECT
    GOLDEN_VEHICLE_ID,
    GOLDEN_CUSTOMER_ID,
    'CONFORMED' AS SOURCE_SYSTEM,
    VEHICLE_ID AS SOURCE_VEHICLE_ID,
    IDENTITY_RESOLUTION_CONFIDENCE AS MATCH_CONFIDENCE,
    MATCH_METHOD,
    'same_source_vehicle_id' AS MATCH_REASON_CODE,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM GOLDEN.GOLDEN_VEHICLE;

  CREATE OR REPLACE TABLE GOLDEN.GOLDEN_ACCOUNT AS
  SELECT
    CONCAT('GACCT_', SUBSTR(SHA2(A.SOURCE_ACCOUNT_ID, 256), 1, 16)) AS GOLDEN_ACCOUNT_ID,
    C.GOLDEN_CUSTOMER_ID,
    A.ACCOUNT_TYPE,
    A.ACCOUNT_STATUS,
    1.000000::NUMBER(10, 6) AS IDENTITY_RESOLUTION_CONFIDENCE,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
  FROM IDENTITY.STD_ACCOUNT A
  LEFT JOIN GOLDEN.GOLDEN_CUSTOMER C
    ON C.PRIMARY_SOURCE_CUSTOMER_ID = A.SOURCE_CUSTOMER_ID;

  CREATE OR REPLACE TABLE GOLDEN.XREF_ACCOUNT_SOURCE AS
  SELECT
    A.GOLDEN_ACCOUNT_ID,
    A.GOLDEN_CUSTOMER_ID,
    'STG_FLEET.FINANCE_BILLING_INVOICES' AS SOURCE_SYSTEM,
    S.SOURCE_ACCOUNT_ID,
    A.IDENTITY_RESOLUTION_CONFIDENCE AS MATCH_CONFIDENCE,
    'deterministic_invoice_customer_id' AS MATCH_METHOD,
    'same_invoice_customer_relationship' AS MATCH_REASON_CODE,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM GOLDEN.GOLDEN_ACCOUNT A
  JOIN IDENTITY.STD_ACCOUNT S
    ON A.GOLDEN_ACCOUNT_ID = CONCAT('GACCT_', SUBSTR(SHA2(S.SOURCE_ACCOUNT_ID, 256), 1, 16));

  CREATE OR REPLACE TABLE GOLDEN.GOLDEN_FUEL_CARD AS
  SELECT
    CONCAT('GFCARD_', SUBSTR(SHA2(F.SOURCE_FUEL_CARD_ID, 256), 1, 16)) AS GOLDEN_FUEL_CARD_ID,
    V.GOLDEN_VEHICLE_ID,
    C.GOLDEN_CUSTOMER_ID,
    F.CARD_STATUS,
    1.000000::NUMBER(10, 6) AS IDENTITY_RESOLUTION_CONFIDENCE,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
  FROM IDENTITY.STD_FUEL_CARD F
  LEFT JOIN GOLDEN.GOLDEN_VEHICLE V
    ON V.VEHICLE_ID = F.SOURCE_VEHICLE_ID
  LEFT JOIN GOLDEN.GOLDEN_CUSTOMER C
    ON C.PRIMARY_SOURCE_CUSTOMER_ID = F.SOURCE_CUSTOMER_ID;

  CREATE OR REPLACE TABLE GOLDEN.XREF_FUEL_CARD_SOURCE AS
  SELECT
    F.GOLDEN_FUEL_CARD_ID,
    F.GOLDEN_VEHICLE_ID,
    F.GOLDEN_CUSTOMER_ID,
    'STG_FLEET.FUEL_CARDS' AS SOURCE_SYSTEM,
    S.SOURCE_FUEL_CARD_ID,
    F.IDENTITY_RESOLUTION_CONFIDENCE AS MATCH_CONFIDENCE,
    'deterministic_fuel_card_id' AS MATCH_METHOD,
    'same_fuel_card_id' AS MATCH_REASON_CODE,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM GOLDEN.GOLDEN_FUEL_CARD F
  JOIN IDENTITY.STD_FUEL_CARD S
    ON F.GOLDEN_FUEL_CARD_ID = CONCAT('GFCARD_', SUBSTR(SHA2(S.SOURCE_FUEL_CARD_ID, 256), 1, 16));

  CREATE OR REPLACE TABLE GOLDEN.XREF_DEVICE_SOURCE AS
  SELECT
    CONCAT('GDEV_', SUBSTR(SHA2(STD_PROVIDER_DEVICE_ID, 256), 1, 16)) AS GOLDEN_DEVICE_ID,
    V.GOLDEN_VEHICLE_ID,
    V.GOLDEN_CUSTOMER_ID,
    D.SOURCE_SYSTEM_ID AS SOURCE_SYSTEM,
    D.SOURCE_DEVICE_ID,
    1.000000::NUMBER(10, 6) AS MATCH_CONFIDENCE,
    'deterministic_provider_device_id' AS MATCH_METHOD,
    'same_device_vehicle_assignment' AS MATCH_REASON_CODE,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM IDENTITY.STD_DEVICE D
  LEFT JOIN GOLDEN.GOLDEN_VEHICLE V
    ON V.VEHICLE_ID = D.SOURCE_VEHICLE_ID;

  CREATE OR REPLACE TABLE GOLDEN.REL_CUSTOMER_VEHICLE AS
  SELECT
    GOLDEN_CUSTOMER_ID,
    GOLDEN_VEHICLE_ID,
    IFF(LOWER(COALESCE(VEHICLE_STATUS, 'active')) = 'active', 'active', 'inactive') AS RELATIONSHIP_STATUS,
    NULL::DATE AS RELATIONSHIP_START_DATE,
    NULL::DATE AS RELATIONSHIP_END_DATE,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM GOLDEN.GOLDEN_VEHICLE
  WHERE GOLDEN_CUSTOMER_ID IS NOT NULL;

  CREATE OR REPLACE TABLE GOLDEN.REL_CUSTOMER_CONTRACT AS
  SELECT
    C.GOLDEN_CUSTOMER_ID,
    L.LEASE_ID AS CONTRACT_ID,
    LOWER(COALESCE(L.LEASE_STATUS, 'active')) AS RELATIONSHIP_STATUS,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM STG_FLEET.LEASING_CONTRACTS L
  JOIN GOLDEN.GOLDEN_CUSTOMER C
    ON C.PRIMARY_SOURCE_CUSTOMER_ID = L.CLIENT_ID
  WHERE L._IS_LATEST_FOR_BUSINESS_KEY = TRUE
    AND L._LATEST_RESOLUTION_STATUS = 'resolved'
    AND L._IS_EXACT_DUPLICATE = FALSE
    AND COALESCE(L._DQ_STATUS, 'passed') = 'passed';

  CREATE OR REPLACE TABLE GOLDEN.REL_VEHICLE_FUEL_CARD AS
  SELECT
    GOLDEN_VEHICLE_ID,
    GOLDEN_FUEL_CARD_ID,
    LOWER(COALESCE(CARD_STATUS, 'active')) AS RELATIONSHIP_STATUS,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM GOLDEN.GOLDEN_FUEL_CARD
  WHERE GOLDEN_VEHICLE_ID IS NOT NULL;

  CREATE OR REPLACE TABLE GOLDEN.REL_VEHICLE_TELEMATICS_DEVICE AS
  SELECT
    GOLDEN_VEHICLE_ID,
    GOLDEN_DEVICE_ID,
    SOURCE_SYSTEM AS PROVIDER_NAME,
    'active' AS RELATIONSHIP_STATUS,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM GOLDEN.XREF_DEVICE_SOURCE
  WHERE GOLDEN_VEHICLE_ID IS NOT NULL;

  CREATE OR REPLACE TABLE GOLDEN.REL_CUSTOMER_PORTAL_ACCOUNT AS
  SELECT DISTINCT
    C.GOLDEN_CUSTOMER_ID,
    P.PORTAL_USER_ID AS PORTAL_ACCOUNT_ID,
    'active' AS RELATIONSHIP_STATUS,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM STG_FLEET.CRM_CLIENT_PORTAL_EVENTS P
  JOIN GOLDEN.GOLDEN_CUSTOMER C
    ON C.PRIMARY_SOURCE_CUSTOMER_ID = P.CLIENT_ID
  WHERE P.PORTAL_USER_ID IS NOT NULL
    AND P.PORTAL_USER_ID <> '';

  CREATE OR REPLACE TABLE GOVERNANCE.IDENTITY_REVIEW_QUEUE AS
  SELECT
    CONCAT('REV_', SUBSTR(SHA2(CONCAT_WS('|', ENTITY_TYPE, SOURCE_RECORD_A, SOURCE_RECORD_B, MATCH_METHOD), 256), 1, 16)) AS REVIEW_CASE_ID,
    ENTITY_TYPE,
    SOURCE_RECORD_A AS CANDIDATE_RECORD_A,
    SOURCE_RECORD_B AS CANDIDATE_RECORD_B,
    MATCH_SCORE,
    MATCH_REASON_CODE AS MATCH_REASON,
    'name_or_identifier_conflict' AS CONFLICTING_ATTRIBUTES,
    'steward_review' AS RECOMMENDED_ACTION,
    'open' AS REVIEW_STATUS,
    NULL::VARCHAR AS REVIEWED_BY,
    NULL::TIMESTAMP_NTZ AS REVIEWED_AT,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM IDENTITY.CUSTOMER_MATCH_CANDIDATE
  WHERE REVIEW_REQUIRED_FLAG = TRUE
  UNION ALL
  SELECT
    CONCAT('REV_', SUBSTR(SHA2(CONCAT_WS('|', ENTITY_TYPE, SOURCE_RECORD_A, SOURCE_RECORD_B, MATCH_METHOD), 256), 1, 16)) AS REVIEW_CASE_ID,
    ENTITY_TYPE,
    SOURCE_RECORD_A AS CANDIDATE_RECORD_A,
    SOURCE_RECORD_B AS CANDIDATE_RECORD_B,
    MATCH_SCORE,
    MATCH_REASON_CODE AS MATCH_REASON,
    'vehicle_identifier_conflict' AS CONFLICTING_ATTRIBUTES,
    'steward_review' AS RECOMMENDED_ACTION,
    'open' AS REVIEW_STATUS,
    NULL::VARCHAR AS REVIEWED_BY,
    NULL::TIMESTAMP_NTZ AS REVIEWED_AT,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS CREATED_AT
  FROM IDENTITY.VEHICLE_MATCH_CANDIDATE
  WHERE REVIEW_REQUIRED_FLAG = TRUE;

  CREATE OR REPLACE TABLE GOLD.CUSTOMER_360_MART AS
  WITH vehicle_metrics AS (
    SELECT
      GOLDEN_CUSTOMER_ID,
      COUNT_IF(RELATIONSHIP_STATUS = 'active') AS ACTIVE_VEHICLE_COUNT
    FROM GOLDEN.REL_CUSTOMER_VEHICLE
    GROUP BY GOLDEN_CUSTOMER_ID
  ),
  contract_metrics AS (
    SELECT
      C.GOLDEN_CUSTOMER_ID,
      COUNT_IF(LOWER(COALESCE(L.LEASE_STATUS, 'active')) = 'active') AS ACTIVE_CONTRACT_COUNT,
      SUM(COALESCE(L.MONTHLY_RENTAL_AMOUNT, 0) + COALESCE(L.MANAGEMENT_FEE_AMOUNT, 0)) AS MONTHLY_TCO
    FROM STG_FLEET.LEASING_CONTRACTS L
    JOIN GOLDEN.XREF_CUSTOMER_SOURCE C
      ON C.SOURCE_CUSTOMER_ID = L.CLIENT_ID
    WHERE L._IS_LATEST_FOR_BUSINESS_KEY = TRUE
      AND L._LATEST_RESOLUTION_STATUS = 'resolved'
      AND L._IS_EXACT_DUPLICATE = FALSE
      AND COALESCE(L._DQ_STATUS, 'passed') = 'passed'
    GROUP BY C.GOLDEN_CUSTOMER_ID
  ),
  fuel_metrics AS (
    SELECT
      C.GOLDEN_CUSTOMER_ID,
      SUM(COALESCE(F.GROSS_AMOUNT, 0)) AS FUEL_COST_90D
    FROM STG_FLEET.FUEL_CARD_TRANSACTIONS F
    JOIN GOLDEN.XREF_CUSTOMER_SOURCE C
      ON C.SOURCE_CUSTOMER_ID = F.CLIENT_ID
    WHERE TO_DATE(F.TRANSACTION_DATETIME) >= DATEADD(day, -90, COALESCE(:BATCH_DATE, CURRENT_DATE()))
    GROUP BY C.GOLDEN_CUSTOMER_ID
  ),
  maintenance_metrics AS (
    SELECT
      C.GOLDEN_CUSTOMER_ID,
      SUM(COALESCE(M.INVOICE_AMOUNT, M.AUTHORISED_AMOUNT, 0)) AS MAINTENANCE_COST_90D
    FROM STG_FLEET.MAINTENANCE_WORK_ORDERS M
    JOIN GOLDEN.XREF_CUSTOMER_SOURCE C
      ON C.SOURCE_CUSTOMER_ID = M.CLIENT_ID
    WHERE TO_DATE(COALESCE(M.CLOSED_DATE, M.OPENED_DATE)) >= DATEADD(day, -90, COALESCE(:BATCH_DATE, CURRENT_DATE()))
      AND M._IS_LATEST_FOR_BUSINESS_KEY = TRUE
      AND M._LATEST_RESOLUTION_STATUS = 'resolved'
      AND M._IS_EXACT_DUPLICATE = FALSE
      AND COALESCE(M._DQ_STATUS, 'passed') = 'passed'
    GROUP BY C.GOLDEN_CUSTOMER_ID
  ),
  ev_metrics AS (
    SELECT
      C.GOLDEN_CUSTOMER_ID,
      SUM(COALESCE(E.GROSS_AMOUNT, 0)) AS EV_CHARGING_COST_90D
    FROM STG_FLEET.EV_CHARGING_SESSIONS E
    JOIN GOLDEN.XREF_CUSTOMER_SOURCE C
      ON C.SOURCE_CUSTOMER_ID = E.CLIENT_ID
    WHERE TO_DATE(E.SESSION_START_DATETIME) >= DATEADD(day, -90, COALESCE(:BATCH_DATE, CURRENT_DATE()))
      AND E._IS_LATEST_FOR_BUSINESS_KEY = TRUE
      AND E._LATEST_RESOLUTION_STATUS = 'resolved'
      AND E._IS_EXACT_DUPLICATE = FALSE
      AND COALESCE(E._DQ_STATUS, 'passed') = 'passed'
    GROUP BY C.GOLDEN_CUSTOMER_ID
  ),
  claim_metrics AS (
    SELECT
      C.GOLDEN_CUSTOMER_ID,
      COUNT_IF(LOWER(COALESCE(I.CLAIM_STATUS, 'open')) NOT IN ('closed', 'settled', 'declined')) AS OPEN_CLAIM_COUNT
    FROM STG_FLEET.INSURANCE_CLAIMS I
    JOIN GOLDEN.XREF_CUSTOMER_SOURCE C
      ON C.SOURCE_CUSTOMER_ID = I.CLIENT_ID
    WHERE I._IS_LATEST_FOR_BUSINESS_KEY = TRUE
      AND I._LATEST_RESOLUTION_STATUS = 'resolved'
      AND I._IS_EXACT_DUPLICATE = FALSE
      AND COALESCE(I._DQ_STATUS, 'passed') = 'passed'
    GROUP BY C.GOLDEN_CUSTOMER_ID
  ),
  portal_metrics AS (
    SELECT
      C.GOLDEN_CUSTOMER_ID,
      LEAST(100, COUNT(*) * 0.5 + COUNT_IF(P.SLA_BREACH_FLAG = 'true') * 5)::NUMBER(18, 6) AS PORTAL_ACTIVITY_SCORE
    FROM STG_FLEET.CRM_CLIENT_PORTAL_EVENTS P
    JOIN GOLDEN.XREF_CUSTOMER_SOURCE C
      ON C.SOURCE_CUSTOMER_ID = P.CLIENT_ID
    WHERE TO_DATE(P.EVENT_DATETIME) >= DATEADD(day, -90, COALESCE(:BATCH_DATE, CURRENT_DATE()))
      AND P._IS_LATEST_FOR_BUSINESS_KEY = TRUE
      AND P._LATEST_RESOLUTION_STATUS = 'resolved'
      AND P._IS_EXACT_DUPLICATE = FALSE
      AND COALESCE(P._DQ_STATUS, 'passed') = 'passed'
    GROUP BY C.GOLDEN_CUSTOMER_ID
  )
  SELECT
    C.GOLDEN_CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_SEGMENT,
    COALESCE(V.ACTIVE_VEHICLE_COUNT, 0) AS ACTIVE_VEHICLE_COUNT,
    COALESCE(K.ACTIVE_CONTRACT_COUNT, 0) AS ACTIVE_CONTRACT_COUNT,
    COALESCE(K.MONTHLY_TCO, 0) AS MONTHLY_TCO,
    COALESCE(M.MAINTENANCE_COST_90D, 0) AS MAINTENANCE_COST_90D,
    COALESCE(F.FUEL_COST_90D, 0) AS FUEL_COST_90D,
    COALESCE(E.EV_CHARGING_COST_90D, 0) AS EV_CHARGING_COST_90D,
    COALESCE(CL.OPEN_CLAIM_COUNT, 0) AS OPEN_CLAIM_COUNT,
    COALESCE(P.PORTAL_ACTIVITY_SCORE, 0) AS PORTAL_ACTIVITY_SCORE,
    LEAST(100, COALESCE(V.ACTIVE_VEHICLE_COUNT, 0) * 1.5 + COALESCE(CL.OPEN_CLAIM_COUNT, 0) * 8)::NUMBER(18, 6) AS SERVICE_RISK_SCORE,
    IFF(COALESCE(V.ACTIVE_VEHICLE_COUNT, 0) > 0, 50, 0)::NUMBER(18, 6) AS FLEET_GROWTH_OPPORTUNITY_SCORE,
    IFF(C.GOLDEN_CUSTOMER_ID IS NOT NULL, 'certified', 'failed') AS DATA_QUALITY_STATUS,
    C.IDENTITY_RESOLUTION_CONFIDENCE,
    :RUN_ID AS CREATED_RUN_ID,
    CURRENT_TIMESTAMP() AS BUILT_AT
  FROM GOLDEN.GOLDEN_CUSTOMER C
  LEFT JOIN vehicle_metrics V
    ON V.GOLDEN_CUSTOMER_ID = C.GOLDEN_CUSTOMER_ID
  LEFT JOIN contract_metrics K
    ON K.GOLDEN_CUSTOMER_ID = C.GOLDEN_CUSTOMER_ID
  LEFT JOIN fuel_metrics F
    ON F.GOLDEN_CUSTOMER_ID = C.GOLDEN_CUSTOMER_ID
  LEFT JOIN maintenance_metrics M
    ON M.GOLDEN_CUSTOMER_ID = C.GOLDEN_CUSTOMER_ID
  LEFT JOIN ev_metrics E
    ON E.GOLDEN_CUSTOMER_ID = C.GOLDEN_CUSTOMER_ID
  LEFT JOIN claim_metrics CL
    ON CL.GOLDEN_CUSTOMER_ID = C.GOLDEN_CUSTOMER_ID
  LEFT JOIN portal_metrics P
    ON P.GOLDEN_CUSTOMER_ID = C.GOLDEN_CUSTOMER_ID;

  INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
  SELECT
    'CUSTOMER360_GOLDEN_CUSTOMER_WITHOUT_XREF',
    COUNT(*),
    0,
    IFF(COUNT(*) = 0, 'passed', 'failed')
  FROM GOLDEN.GOLDEN_CUSTOMER C
  LEFT JOIN GOLDEN.XREF_CUSTOMER_SOURCE X
    ON X.GOLDEN_CUSTOMER_ID = C.GOLDEN_CUSTOMER_ID
  WHERE X.GOLDEN_CUSTOMER_ID IS NULL;

  INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
  SELECT
    'CUSTOMER360_CONFIDENCE_MISSING',
    COUNT(*),
    0,
    IFF(COUNT(*) = 0, 'passed', 'failed')
  FROM GOLD.CUSTOMER_360_MART
  WHERE IDENTITY_RESOLUTION_CONFIDENCE IS NULL;

  RETURN 'Built Customer 360 identity resolution for run_id=' || RUN_ID;
END;
$$;

CREATE OR REPLACE VIEW SEMANTIC.CUSTOMER_360 AS
SELECT
  GOLDEN_CUSTOMER_ID,
  CUSTOMER_NAME,
  CUSTOMER_SEGMENT,
  ACTIVE_VEHICLE_COUNT,
  ACTIVE_CONTRACT_COUNT,
  MONTHLY_TCO,
  MAINTENANCE_COST_90D,
  FUEL_COST_90D,
  EV_CHARGING_COST_90D,
  OPEN_CLAIM_COUNT,
  PORTAL_ACTIVITY_SCORE,
  SERVICE_RISK_SCORE,
  FLEET_GROWTH_OPPORTUNITY_SCORE,
  DATA_QUALITY_STATUS,
  IDENTITY_RESOLUTION_CONFIDENCE
FROM GOLD.CUSTOMER_360_MART
WHERE DATA_QUALITY_STATUS = 'certified';

CREATE OR REPLACE VIEW SEMANTIC.CUSTOMER_FLEET_COST_SUMMARY AS
SELECT
  GOLDEN_CUSTOMER_ID,
  CUSTOMER_NAME,
  MONTHLY_TCO,
  MAINTENANCE_COST_90D,
  FUEL_COST_90D,
  EV_CHARGING_COST_90D,
  IDENTITY_RESOLUTION_CONFIDENCE
FROM SEMANTIC.CUSTOMER_360;

CREATE OR REPLACE VIEW SEMANTIC.CUSTOMER_SERVICE_RISK_SUMMARY AS
SELECT
  GOLDEN_CUSTOMER_ID,
  CUSTOMER_NAME,
  ACTIVE_VEHICLE_COUNT,
  OPEN_CLAIM_COUNT,
  SERVICE_RISK_SCORE,
  DATA_QUALITY_STATUS,
  IDENTITY_RESOLUTION_CONFIDENCE
FROM SEMANTIC.CUSTOMER_360;

CREATE OR REPLACE VIEW SEMANTIC.CUSTOMER_GROWTH_OPPORTUNITY AS
SELECT
  GOLDEN_CUSTOMER_ID,
  CUSTOMER_NAME,
  ACTIVE_VEHICLE_COUNT,
  FLEET_GROWTH_OPPORTUNITY_SCORE,
  IDENTITY_RESOLUTION_CONFIDENCE
FROM SEMANTIC.CUSTOMER_360;

-- Example execution:
-- CALL IDENTITY.BUILD_CUSTOMER360_IDENTITY('2026-05-26', 'RUN_CUSTOMER360_20260526');
