-- Element Fleet Services MVP SIT setup for Snowflake.
-- Scope: STG_FLEET, CONFORMED, and AUDIT only.
-- Phase-two GOLD, FEATURES, and SEMANTIC are intentionally excluded.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS FLEET_MVP_SIT_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS FLEET_MVP_SIT;
USE DATABASE FLEET_MVP_SIT;
USE WAREHOUSE FLEET_MVP_SIT_WH;

CREATE SCHEMA IF NOT EXISTS STG_FLEET;
CREATE SCHEMA IF NOT EXISTS CONFORMED;
CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE OR REPLACE FILE FORMAT STG_FLEET.PARQUET_FF
  TYPE = PARQUET
  USE_VECTORIZED_SCANNER = TRUE;

-- One-time setup.
-- Replace <AZURE_TENANT_ID> before running. The Azure Portal URL currently
-- indicates tenant emilyg888gmail.onmicrosoft.com, but Snowflake commonly uses
-- the tenant GUID for this value.
CREATE STORAGE INTEGRATION IF NOT EXISTS FLEET_MVP_ADLS_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = AZURE
  ENABLED = TRUE
  AZURE_TENANT_ID = '<AZURE_TENANT_ID>'
  STORAGE_ALLOWED_LOCATIONS = (
    'azure://emilygcovidreportingdl.blob.core.windows.net/fabric-foundry-sit/staging/'
  );

-- After creating the integration, run this and grant consent in Azure.
DESC STORAGE INTEGRATION FLEET_MVP_ADLS_INT;

CREATE OR REPLACE STAGE STG_FLEET.ADLS_STAGING_STAGE
  URL = 'azure://emilygcovidreportingdl.blob.core.windows.net/fabric-foundry-sit/staging/'
  STORAGE_INTEGRATION = FLEET_MVP_ADLS_INT
  FILE_FORMAT = STG_FLEET.PARQUET_FF;

LIST @STG_FLEET.ADLS_STAGING_STAGE;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.CLIENTS_EXT (
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  CLIENT_NAME VARCHAR AS (VALUE:client_name::VARCHAR),
  INDUSTRY_SEGMENT VARCHAR AS (VALUE:industry_segment::VARCHAR),
  HEADQUARTERS_STATE VARCHAR AS (VALUE:headquarters_state::VARCHAR),
  FLEET_SIZE_BAND VARCHAR AS (VALUE:fleet_size_band::VARCHAR),
  CONTRACT_START_DATE DATE AS (TRY_TO_DATE(VALUE:contract_start_date::VARCHAR)),
  CLIENT_STATUS VARCHAR AS (VALUE:client_status::VARCHAR),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  _LOAD_TYPE VARCHAR AS (VALUE:_load_type::VARCHAR),
  _SOURCE_EXTRACT_DATE DATE AS (TRY_TO_DATE(VALUE:_source_extract_date::VARCHAR)),
  _DELTA_ACTION VARCHAR AS (VALUE:_delta_action::VARCHAR),
  _BATCH_DATE DATE AS (TRY_TO_DATE(VALUE:_batch_date::VARCHAR)),
  _RECORD_HASH VARCHAR AS (VALUE:_record_hash::VARCHAR),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=clients/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

ALTER EXTERNAL TABLE STG_FLEET.CLIENTS_EXT REFRESH;

CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.CLIENTS AS
SELECT *
FROM STG_FLEET.CLIENTS_EXT;

CREATE OR REPLACE TABLE CONFORMED.DIM_CLIENT (
  CLIENT_SK NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  CLIENT_ID VARCHAR,
  CLIENT_NAME VARCHAR,
  INDUSTRY_SEGMENT VARCHAR,
  HEADQUARTERS_STATE VARCHAR,
  FLEET_SIZE_BAND VARCHAR,
  CONTRACT_START_DATE DATE,
  CLIENT_STATUS VARCHAR,
  BUSINESS_KEY VARCHAR,
  EFFECTIVE_FROM TIMESTAMP_NTZ,
  EFFECTIVE_TO TIMESTAMP_NTZ,
  IS_CURRENT BOOLEAN,
  DELETED_FLAG BOOLEAN,
  SOURCE_EFFECTIVE_AT TIMESTAMP_NTZ,
  SOURCE_UPDATED_AT TIMESTAMP_NTZ,
  SOURCE_RECORD_HASH VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE AUDIT.SIT_CHECK_RESULTS (
  CHECK_NAME VARCHAR,
  CHECK_VALUE NUMBER,
  EXPECTED_VALUE NUMBER,
  CHECK_STATUS VARCHAR,
  CHECKED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Load day 1 only into STG_FLEET.CLIENTS, then run the SCD merge block below.
-- For day 2, replace the transient table with the 2026-05-26 partition and
-- run the same merge block again.
--
-- Day 1:
-- CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.CLIENTS AS
-- SELECT * FROM STG_FLEET.CLIENTS_EXT WHERE _BATCH_DATE = '2026-05-25';
--
-- Day 2:
-- CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.CLIENTS AS
-- SELECT * FROM STG_FLEET.CLIENTS_EXT WHERE _BATCH_DATE = '2026-05-26';

-- Expire changed current rows.
UPDATE CONFORMED.DIM_CLIENT TGT
SET
  EFFECTIVE_TO = SRC.EFFECTIVE_AT,
  IS_CURRENT = FALSE,
  UPDATED_AT = CURRENT_TIMESTAMP()
FROM STG_FLEET.CLIENTS SRC
WHERE TGT.CLIENT_ID = SRC.CLIENT_ID
  AND TGT.IS_CURRENT = TRUE
  AND SRC._IS_LATEST_FOR_BUSINESS_KEY = TRUE
  AND SRC._LATEST_RESOLUTION_STATUS = 'resolved'
  AND SRC._IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(SRC._DQ_STATUS, 'passed') = 'passed'
  AND COALESCE(SRC._DELTA_ACTION, 'UPSERT') <> 'DELETE'
  AND TGT.SOURCE_RECORD_HASH <> SRC._RECORD_HASH;

-- Insert new current rows for new or changed business keys.
INSERT INTO CONFORMED.DIM_CLIENT (
  CLIENT_ID,
  CLIENT_NAME,
  INDUSTRY_SEGMENT,
  HEADQUARTERS_STATE,
  FLEET_SIZE_BAND,
  CONTRACT_START_DATE,
  CLIENT_STATUS,
  BUSINESS_KEY,
  EFFECTIVE_FROM,
  EFFECTIVE_TO,
  IS_CURRENT,
  DELETED_FLAG,
  SOURCE_EFFECTIVE_AT,
  SOURCE_UPDATED_AT,
  SOURCE_RECORD_HASH,
  CREATED_AT,
  UPDATED_AT
)
SELECT
  SRC.CLIENT_ID,
  SRC.CLIENT_NAME,
  SRC.INDUSTRY_SEGMENT,
  SRC.HEADQUARTERS_STATE,
  SRC.FLEET_SIZE_BAND,
  SRC.CONTRACT_START_DATE,
  SRC.CLIENT_STATUS,
  SRC.CLIENT_ID AS BUSINESS_KEY,
  SRC.EFFECTIVE_AT AS EFFECTIVE_FROM,
  '9999-12-31'::TIMESTAMP_NTZ AS EFFECTIVE_TO,
  TRUE AS IS_CURRENT,
  FALSE AS DELETED_FLAG,
  SRC.EFFECTIVE_AT AS SOURCE_EFFECTIVE_AT,
  SRC.UPDATED_AT AS SOURCE_UPDATED_AT,
  SRC._RECORD_HASH AS SOURCE_RECORD_HASH,
  CURRENT_TIMESTAMP() AS CREATED_AT,
  CURRENT_TIMESTAMP() AS UPDATED_AT
FROM STG_FLEET.CLIENTS SRC
LEFT JOIN CONFORMED.DIM_CLIENT TGT
  ON TGT.CLIENT_ID = SRC.CLIENT_ID
 AND TGT.IS_CURRENT = TRUE
WHERE SRC._IS_LATEST_FOR_BUSINESS_KEY = TRUE
  AND SRC._LATEST_RESOLUTION_STATUS = 'resolved'
  AND SRC._IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(SRC._DQ_STATUS, 'passed') = 'passed'
  AND COALESCE(SRC._DELTA_ACTION, 'UPSERT') <> 'DELETE'
  AND (TGT.CLIENT_ID IS NULL OR TGT.SOURCE_RECORD_HASH <> SRC._RECORD_HASH);

-- Soft-delete missing rows for authoritative full snapshots.
UPDATE CONFORMED.DIM_CLIENT TGT
SET
  EFFECTIVE_TO = CURRENT_TIMESTAMP(),
  IS_CURRENT = FALSE,
  DELETED_FLAG = TRUE,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TGT.IS_CURRENT = TRUE
  AND NOT EXISTS (
    SELECT 1
    FROM STG_FLEET.CLIENTS SRC
    WHERE SRC.CLIENT_ID = TGT.CLIENT_ID
      AND SRC._LOAD_TYPE = 'full'
  )
  AND EXISTS (
    SELECT 1
    FROM STG_FLEET.CLIENTS SRC
    WHERE SRC._LOAD_TYPE = 'full'
  );

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT 'DIM_CLIENT_CURRENT_ROWS', COUNT(*), 18, IFF(COUNT(*) = 18, 'passed', 'failed')
FROM CONFORMED.DIM_CLIENT
WHERE IS_CURRENT = TRUE;

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT 'DIM_CLIENT_CLOSED_CHANGED_ROWS', COUNT(*), 8, IFF(COUNT(*) = 8, 'passed', 'failed')
FROM CONFORMED.DIM_CLIENT
WHERE IS_CURRENT = FALSE
  AND DELETED_FLAG = FALSE;

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT 'DIM_CLIENT_SOFT_DELETED_ROWS', COUNT(*), 0, IFF(COUNT(*) = 0, 'passed', 'failed')
FROM CONFORMED.DIM_CLIENT
WHERE DELETED_FLAG = TRUE;

SELECT *
FROM AUDIT.SIT_CHECK_RESULTS
ORDER BY CHECKED_AT, CHECK_NAME;
