-- Element Fleet Services Snowflake stream-based DIM_VEHICLE population.
-- Run after `element_fleet_snowflake_sit_setup.sql` has loaded DIM_CLIENT.
--
-- Purpose:
--   ADLS STAGING Parquet -> STG_FLEET.VEHICLES_EXT
--   -> STG_FLEET.VEHICLES_LOAD
--   -> STG_FLEET.VEHICLES_LOAD_STREAM
--   -> CONFORMED.DIM_VEHICLE

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FLEET_MVP_SIT_WH;
USE DATABASE FLEET_MVP_SIT;

CREATE SCHEMA IF NOT EXISTS STG_FLEET;
CREATE SCHEMA IF NOT EXISTS CONFORMED;
CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE OR REPLACE EXTERNAL TABLE STG_FLEET.VEHICLES_EXT (
  VEHICLE_ID VARCHAR AS (VALUE:vehicle_id::VARCHAR),
  CLIENT_ID VARCHAR AS (VALUE:client_id::VARCHAR),
  VIN VARCHAR AS (VALUE:vin::VARCHAR),
  REGISTRATION_PLATE VARCHAR AS (VALUE:registration_plate::VARCHAR),
  ASSET_TYPE VARCHAR AS (VALUE:asset_type::VARCHAR),
  MAKE VARCHAR AS (VALUE:make::VARCHAR),
  MODEL VARCHAR AS (VALUE:model::VARCHAR),
  MODEL_YEAR NUMBER AS (TRY_TO_NUMBER(VALUE:model_year::VARCHAR)),
  FUEL_TYPE VARCHAR AS (VALUE:fuel_type::VARCHAR),
  STATE_REGISTERED VARCHAR AS (VALUE:state_registered::VARCHAR),
  ODOMETER_KM NUMBER AS (TRY_TO_NUMBER(VALUE:odometer_km::VARCHAR)),
  IN_SERVICE_DATE DATE AS (TRY_TO_DATE(VALUE:in_service_date::VARCHAR)),
  LEASE_END_DATE DATE AS (TRY_TO_DATE(VALUE:lease_end_date::VARCHAR)),
  VEHICLE_STATUS VARCHAR AS (VALUE:vehicle_status::VARCHAR),
  TELEMATICS_DEVICE_ID VARCHAR AS (VALUE:telematics_device_id::VARCHAR),
  TELEMATICS_DEVICE_MODEL VARCHAR AS (VALUE:telematics_device_model::VARCHAR),
  TELEMATICS_INSTALL_DATE DATE AS (TRY_TO_DATE(VALUE:telematics_install_date::VARCHAR)),
  UPDATED_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:updated_at::VARCHAR)),
  EFFECTIVE_AT TIMESTAMP_NTZ AS (TRY_TO_TIMESTAMP_NTZ(VALUE:effective_at::VARCHAR)),
  _LOAD_TYPE VARCHAR AS (VALUE:_load_type::VARCHAR),
  _SOURCE_EXTRACT_DATE DATE AS (TRY_TO_DATE(VALUE:_source_extract_date::VARCHAR)),
  _DELTA_ACTION VARCHAR AS (VALUE:_delta_action::VARCHAR),
  _BATCH_DATE DATE AS (TRY_TO_DATE(VALUE:_batch_date::VARCHAR)),
  _RECORD_HASH VARCHAR AS (VALUE:_record_hash::VARCHAR),
  _IS_EXACT_DUPLICATE BOOLEAN AS (VALUE:_is_exact_duplicate::BOOLEAN),
  _IS_LATEST_FOR_BUSINESS_KEY BOOLEAN AS (VALUE:_is_latest_for_business_key::BOOLEAN),
  _LATEST_RESOLUTION_STATUS VARCHAR AS (VALUE:_latest_resolution_status::VARCHAR),
  _DQ_STATUS VARCHAR AS (VALUE:_dq_status::VARCHAR)
)
WITH LOCATION = @STG_FLEET.ADLS_STAGING_STAGE/domain=fleet_management/dataset=vehicles/
FILE_FORMAT = STG_FLEET.PARQUET_FF
AUTO_REFRESH = FALSE;

ALTER EXTERNAL TABLE STG_FLEET.VEHICLES_EXT REFRESH;

CREATE OR REPLACE TRANSIENT TABLE STG_FLEET.VEHICLES_LOAD AS
SELECT *
FROM STG_FLEET.VEHICLES_EXT
WHERE 1 = 0;

CREATE OR REPLACE STREAM STG_FLEET.VEHICLES_LOAD_STREAM
  ON TABLE STG_FLEET.VEHICLES_LOAD
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TABLE CONFORMED.DIM_VEHICLE (
  VEHICLE_SK NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  VEHICLE_ID VARCHAR,
  CLIENT_SK NUMBER,
  CLIENT_ID VARCHAR,
  VIN VARCHAR,
  REGISTRATION_PLATE VARCHAR,
  ASSET_TYPE VARCHAR,
  MAKE VARCHAR,
  MODEL VARCHAR,
  MODEL_YEAR NUMBER,
  FUEL_TYPE VARCHAR,
  STATE_REGISTERED VARCHAR,
  ODOMETER_KM NUMBER,
  IN_SERVICE_DATE DATE,
  LEASE_END_DATE DATE,
  VEHICLE_STATUS VARCHAR,
  TELEMATICS_DEVICE_ID VARCHAR,
  TELEMATICS_DEVICE_MODEL VARCHAR,
  TELEMATICS_INSTALL_DATE DATE,
  BUSINESS_KEY VARCHAR,
  EFFECTIVE_FROM TIMESTAMP_NTZ,
  EFFECTIVE_TO TIMESTAMP_NTZ,
  IS_CURRENT BOOLEAN,
  DELETED_FLAG BOOLEAN,
  SOURCE_EFFECTIVE_AT TIMESTAMP_NTZ,
  SOURCE_UPDATED_AT TIMESTAMP_NTZ,
  SOURCE_RECORD_HASH VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS AUDIT.SIT_CHECK_RESULTS (
  CHECK_NAME VARCHAR,
  CHECK_VALUE NUMBER,
  EXPECTED_VALUE NUMBER,
  CHECK_STATUS VARCHAR,
  CHECKED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Day 1 full extract enters the controlled staging table and stream.
TRUNCATE TABLE STG_FLEET.VEHICLES_LOAD;

INSERT INTO STG_FLEET.VEHICLES_LOAD
SELECT *
FROM STG_FLEET.VEHICLES_EXT
WHERE _BATCH_DATE = '2026-05-25';

BEGIN;

UPDATE CONFORMED.DIM_VEHICLE TGT
SET
  EFFECTIVE_TO = SRC.EFFECTIVE_AT,
  IS_CURRENT = FALSE,
  UPDATED_AT = CURRENT_TIMESTAMP()
FROM STG_FLEET.VEHICLES_LOAD_STREAM SRC
JOIN CONFORMED.DIM_CLIENT PARENT
  ON PARENT.CLIENT_ID = SRC.CLIENT_ID
 AND PARENT.IS_CURRENT = TRUE
WHERE TGT.VEHICLE_ID = SRC.VEHICLE_ID
  AND TGT.IS_CURRENT = TRUE
  AND SRC.METADATA$ACTION = 'INSERT'
  AND SRC._IS_LATEST_FOR_BUSINESS_KEY = TRUE
  AND SRC._LATEST_RESOLUTION_STATUS = 'resolved'
  AND SRC._IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(SRC._DQ_STATUS, 'passed') = 'passed'
  AND COALESCE(SRC._DELTA_ACTION, 'UPSERT') <> 'DELETE'
  AND TGT.SOURCE_RECORD_HASH <> SRC._RECORD_HASH;

INSERT INTO CONFORMED.DIM_VEHICLE (
  VEHICLE_ID,
  CLIENT_SK,
  CLIENT_ID,
  VIN,
  REGISTRATION_PLATE,
  ASSET_TYPE,
  MAKE,
  MODEL,
  MODEL_YEAR,
  FUEL_TYPE,
  STATE_REGISTERED,
  ODOMETER_KM,
  IN_SERVICE_DATE,
  LEASE_END_DATE,
  VEHICLE_STATUS,
  TELEMATICS_DEVICE_ID,
  TELEMATICS_DEVICE_MODEL,
  TELEMATICS_INSTALL_DATE,
  BUSINESS_KEY,
  EFFECTIVE_FROM,
  EFFECTIVE_TO,
  IS_CURRENT,
  DELETED_FLAG,
  SOURCE_EFFECTIVE_AT,
  SOURCE_UPDATED_AT,
  SOURCE_RECORD_HASH,
  CREATED_AT,
  UPDATED_AT
)
SELECT
  SRC.VEHICLE_ID,
  PARENT.CLIENT_SK,
  SRC.CLIENT_ID,
  SRC.VIN,
  SRC.REGISTRATION_PLATE,
  SRC.ASSET_TYPE,
  SRC.MAKE,
  SRC.MODEL,
  SRC.MODEL_YEAR,
  SRC.FUEL_TYPE,
  SRC.STATE_REGISTERED,
  SRC.ODOMETER_KM,
  SRC.IN_SERVICE_DATE,
  SRC.LEASE_END_DATE,
  SRC.VEHICLE_STATUS,
  SRC.TELEMATICS_DEVICE_ID,
  SRC.TELEMATICS_DEVICE_MODEL,
  SRC.TELEMATICS_INSTALL_DATE,
  SRC.VEHICLE_ID AS BUSINESS_KEY,
  SRC.EFFECTIVE_AT AS EFFECTIVE_FROM,
  '9999-12-31'::TIMESTAMP_NTZ AS EFFECTIVE_TO,
  TRUE AS IS_CURRENT,
  FALSE AS DELETED_FLAG,
  SRC.EFFECTIVE_AT AS SOURCE_EFFECTIVE_AT,
  SRC.UPDATED_AT AS SOURCE_UPDATED_AT,
  SRC._RECORD_HASH AS SOURCE_RECORD_HASH,
  CURRENT_TIMESTAMP() AS CREATED_AT,
  CURRENT_TIMESTAMP() AS UPDATED_AT
FROM STG_FLEET.VEHICLES_LOAD_STREAM SRC
JOIN CONFORMED.DIM_CLIENT PARENT
  ON PARENT.CLIENT_ID = SRC.CLIENT_ID
 AND PARENT.IS_CURRENT = TRUE
LEFT JOIN CONFORMED.DIM_VEHICLE TGT
  ON TGT.VEHICLE_ID = SRC.VEHICLE_ID
 AND TGT.IS_CURRENT = TRUE
WHERE SRC.METADATA$ACTION = 'INSERT'
  AND SRC._IS_LATEST_FOR_BUSINESS_KEY = TRUE
  AND SRC._LATEST_RESOLUTION_STATUS = 'resolved'
  AND SRC._IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(SRC._DQ_STATUS, 'passed') = 'passed'
  AND COALESCE(SRC._DELTA_ACTION, 'UPSERT') <> 'DELETE'
  AND (TGT.VEHICLE_ID IS NULL OR TGT.SOURCE_RECORD_HASH <> SRC._RECORD_HASH);

UPDATE CONFORMED.DIM_VEHICLE TGT
SET
  EFFECTIVE_TO = CURRENT_TIMESTAMP(),
  IS_CURRENT = FALSE,
  DELETED_FLAG = TRUE,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TGT.IS_CURRENT = TRUE
  AND NOT EXISTS (
    SELECT 1
    FROM STG_FLEET.VEHICLES_LOAD SRC
    WHERE SRC.VEHICLE_ID = TGT.VEHICLE_ID
      AND SRC._LOAD_TYPE = 'full'
  )
  AND EXISTS (
    SELECT 1
    FROM STG_FLEET.VEHICLES_LOAD SRC
    WHERE SRC._LOAD_TYPE = 'full'
  );

COMMIT;

-- Day 2 full extract enters the same controlled staging table and stream.
TRUNCATE TABLE STG_FLEET.VEHICLES_LOAD;

INSERT INTO STG_FLEET.VEHICLES_LOAD
SELECT *
FROM STG_FLEET.VEHICLES_EXT
WHERE _BATCH_DATE = '2026-05-26';

BEGIN;

UPDATE CONFORMED.DIM_VEHICLE TGT
SET
  EFFECTIVE_TO = SRC.EFFECTIVE_AT,
  IS_CURRENT = FALSE,
  UPDATED_AT = CURRENT_TIMESTAMP()
FROM STG_FLEET.VEHICLES_LOAD_STREAM SRC
JOIN CONFORMED.DIM_CLIENT PARENT
  ON PARENT.CLIENT_ID = SRC.CLIENT_ID
 AND PARENT.IS_CURRENT = TRUE
WHERE TGT.VEHICLE_ID = SRC.VEHICLE_ID
  AND TGT.IS_CURRENT = TRUE
  AND SRC.METADATA$ACTION = 'INSERT'
  AND SRC._IS_LATEST_FOR_BUSINESS_KEY = TRUE
  AND SRC._LATEST_RESOLUTION_STATUS = 'resolved'
  AND SRC._IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(SRC._DQ_STATUS, 'passed') = 'passed'
  AND COALESCE(SRC._DELTA_ACTION, 'UPSERT') <> 'DELETE'
  AND TGT.SOURCE_RECORD_HASH <> SRC._RECORD_HASH;

INSERT INTO CONFORMED.DIM_VEHICLE (
  VEHICLE_ID,
  CLIENT_SK,
  CLIENT_ID,
  VIN,
  REGISTRATION_PLATE,
  ASSET_TYPE,
  MAKE,
  MODEL,
  MODEL_YEAR,
  FUEL_TYPE,
  STATE_REGISTERED,
  ODOMETER_KM,
  IN_SERVICE_DATE,
  LEASE_END_DATE,
  VEHICLE_STATUS,
  TELEMATICS_DEVICE_ID,
  TELEMATICS_DEVICE_MODEL,
  TELEMATICS_INSTALL_DATE,
  BUSINESS_KEY,
  EFFECTIVE_FROM,
  EFFECTIVE_TO,
  IS_CURRENT,
  DELETED_FLAG,
  SOURCE_EFFECTIVE_AT,
  SOURCE_UPDATED_AT,
  SOURCE_RECORD_HASH,
  CREATED_AT,
  UPDATED_AT
)
SELECT
  SRC.VEHICLE_ID,
  PARENT.CLIENT_SK,
  SRC.CLIENT_ID,
  SRC.VIN,
  SRC.REGISTRATION_PLATE,
  SRC.ASSET_TYPE,
  SRC.MAKE,
  SRC.MODEL,
  SRC.MODEL_YEAR,
  SRC.FUEL_TYPE,
  SRC.STATE_REGISTERED,
  SRC.ODOMETER_KM,
  SRC.IN_SERVICE_DATE,
  SRC.LEASE_END_DATE,
  SRC.VEHICLE_STATUS,
  SRC.TELEMATICS_DEVICE_ID,
  SRC.TELEMATICS_DEVICE_MODEL,
  SRC.TELEMATICS_INSTALL_DATE,
  SRC.VEHICLE_ID AS BUSINESS_KEY,
  SRC.EFFECTIVE_AT AS EFFECTIVE_FROM,
  '9999-12-31'::TIMESTAMP_NTZ AS EFFECTIVE_TO,
  TRUE AS IS_CURRENT,
  FALSE AS DELETED_FLAG,
  SRC.EFFECTIVE_AT AS SOURCE_EFFECTIVE_AT,
  SRC.UPDATED_AT AS SOURCE_UPDATED_AT,
  SRC._RECORD_HASH AS SOURCE_RECORD_HASH,
  CURRENT_TIMESTAMP() AS CREATED_AT,
  CURRENT_TIMESTAMP() AS UPDATED_AT
FROM STG_FLEET.VEHICLES_LOAD_STREAM SRC
JOIN CONFORMED.DIM_CLIENT PARENT
  ON PARENT.CLIENT_ID = SRC.CLIENT_ID
 AND PARENT.IS_CURRENT = TRUE
LEFT JOIN CONFORMED.DIM_VEHICLE TGT
  ON TGT.VEHICLE_ID = SRC.VEHICLE_ID
 AND TGT.IS_CURRENT = TRUE
WHERE SRC.METADATA$ACTION = 'INSERT'
  AND SRC._IS_LATEST_FOR_BUSINESS_KEY = TRUE
  AND SRC._LATEST_RESOLUTION_STATUS = 'resolved'
  AND SRC._IS_EXACT_DUPLICATE = FALSE
  AND COALESCE(SRC._DQ_STATUS, 'passed') = 'passed'
  AND COALESCE(SRC._DELTA_ACTION, 'UPSERT') <> 'DELETE'
  AND (TGT.VEHICLE_ID IS NULL OR TGT.SOURCE_RECORD_HASH <> SRC._RECORD_HASH);

UPDATE CONFORMED.DIM_VEHICLE TGT
SET
  EFFECTIVE_TO = CURRENT_TIMESTAMP(),
  IS_CURRENT = FALSE,
  DELETED_FLAG = TRUE,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TGT.IS_CURRENT = TRUE
  AND NOT EXISTS (
    SELECT 1
    FROM STG_FLEET.VEHICLES_LOAD SRC
    WHERE SRC.VEHICLE_ID = TGT.VEHICLE_ID
      AND SRC._LOAD_TYPE = 'full'
  )
  AND EXISTS (
    SELECT 1
    FROM STG_FLEET.VEHICLES_LOAD SRC
    WHERE SRC._LOAD_TYPE = 'full'
  );

COMMIT;

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT
  'DIM_VEHICLE_CURRENT_ROWS_STREAM',
  COUNT(*),
  150,
  IFF(COUNT(*) = 150, 'passed', 'failed')
FROM CONFORMED.DIM_VEHICLE
WHERE IS_CURRENT = TRUE;

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT
  'DIM_VEHICLE_CLOSED_CHANGED_ROWS_STREAM',
  COUNT(*),
  8,
  IFF(COUNT(*) = 8, 'passed', 'failed')
FROM CONFORMED.DIM_VEHICLE
WHERE IS_CURRENT = FALSE
  AND DELETED_FLAG = FALSE;

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT
  'DIM_VEHICLE_SOFT_DELETED_ROWS_STREAM',
  COUNT(*),
  0,
  IFF(COUNT(*) = 0, 'passed', 'failed')
FROM CONFORMED.DIM_VEHICLE
WHERE DELETED_FLAG = TRUE;

INSERT INTO AUDIT.SIT_CHECK_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
WITH unresolved_client_fk AS (
  SELECT VEHICLE_ID
  FROM CONFORMED.DIM_VEHICLE
  WHERE IS_CURRENT = TRUE
    AND CLIENT_SK IS NULL
)
SELECT
  'DIM_VEHICLE_UNRESOLVED_CLIENT_FK_STREAM',
  COUNT(*),
  0,
  IFF(COUNT(*) = 0, 'passed', 'failed')
FROM unresolved_client_fk;

SELECT *
FROM AUDIT.SIT_CHECK_RESULTS
WHERE CHECK_NAME LIKE 'DIM_VEHICLE%STREAM'
ORDER BY CHECKED_AT, CHECK_NAME;

SELECT
  VEHICLE_ID,
  CLIENT_ID,
  CLIENT_SK,
  MAKE,
  MODEL,
  VEHICLE_STATUS,
  EFFECTIVE_FROM,
  EFFECTIVE_TO,
  IS_CURRENT,
  DELETED_FLAG
FROM CONFORMED.DIM_VEHICLE
WHERE VEHICLE_ID IN (
  SELECT D1.VEHICLE_ID
  FROM STG_FLEET.VEHICLES_EXT D1
  JOIN STG_FLEET.VEHICLES_EXT D2
    ON D2.VEHICLE_ID = D1.VEHICLE_ID
   AND D2._BATCH_DATE = '2026-05-26'
  WHERE D1._BATCH_DATE = '2026-05-25'
    AND D1._RECORD_HASH <> D2._RECORD_HASH
)
ORDER BY VEHICLE_ID, EFFECTIVE_FROM;
