-- Fleet Services Fuel Anomaly Detection feature-layer MVP.
-- Scope: FEATURES layer only. No GOLD or SEMANTIC objects are created here.
--
-- Input contract:
--   CONFORMED.FACT_FUEL_TRANSACTION
--   CONFORMED.FACT_TELEMATICS_DAILY_SUMMARY
--   CONFORMED.DIM_FUEL_CARD
--   CONFORMED.DIM_VEHICLE
--   CONFORMED.DIM_CLIENT
--
-- Output:
--   FEATURES.FEATURE_FUEL_ANOMALY_SCORE

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FLEET_MVP_SIT_WH;
USE DATABASE FLEET_MVP_SIT;

CREATE SCHEMA IF NOT EXISTS FEATURES;
CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE TABLE IF NOT EXISTS FEATURES.FEATURE_FUEL_ANOMALY_SCORE (
  FUEL_TRANSACTION_ID VARCHAR,
  FUEL_CARD_ID VARCHAR,
  VEHICLE_ID VARCHAR,
  VEHICLE_SK NUMBER,
  CLIENT_ID VARCHAR,
  CLIENT_SK NUMBER,
  TRANSACTION_DATETIME TIMESTAMP_NTZ,
  TRANSACTION_DATE DATE,
  MERCHANT_STATE VARCHAR,
  FUEL_PRODUCT VARCHAR,
  LITRES NUMBER(18, 2),
  GROSS_AMOUNT NUMBER(18, 2),
  DISTANCE_KM NUMBER(18, 2),
  FUEL_COST_PER_KM NUMBER(18, 6),
  TRANSACTION_FREQUENCY_7D NUMBER,
  MULTIPLE_FILL_FLAG BOOLEAN,
  NO_USAGE_MATCH_FLAG BOOLEAN,
  HIGH_VALUE_TRANSACTION_FLAG BOOLEAN,
  FUEL_CARD_VEHICLE_MISMATCH_FLAG BOOLEAN,
  FUEL_ANOMALY_SCORE NUMBER,
  ANOMALY_REASON_CODES VARCHAR,
  FEATURE_VERSION VARCHAR,
  SCORED_AT TIMESTAMP_NTZ,
  BATCH_DATE DATE,
  SOURCE_RECORD_HASH VARCHAR
);

CREATE OR REPLACE PROCEDURE FEATURES.BUILD_FEATURE_FUEL_ANOMALY_SCORE(BATCH_DATE DATE)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'run'
AS
$$
def run(session, batch_date):
    batch_filter = ""
    if batch_date is not None:
        batch_filter = f"WHERE TO_DATE(TRANSACTION_DATETIME) <= TO_DATE('{batch_date}')"

    session.sql(f"""
CREATE OR REPLACE TABLE FEATURES.FEATURE_FUEL_ANOMALY_SCORE AS
WITH fuel_txn AS (
  SELECT
    FUEL_TRANSACTION_ID,
    FUEL_CARD_ID,
    VEHICLE_ID,
    CLIENT_ID,
    TRANSACTION_DATETIME,
    TO_DATE(TRANSACTION_DATETIME) AS TRANSACTION_DATE,
    MERCHANT_STATE,
    FUEL_PRODUCT,
    LITRES,
    GROSS_AMOUNT,
    EXCEPTION_FLAG,
    SOURCE_RECORD_HASH
  FROM CONFORMED.FACT_FUEL_TRANSACTION
  {batch_filter}
),
txn_enriched AS (
  SELECT
    TXN.FUEL_TRANSACTION_ID,
    TXN.FUEL_CARD_ID,
    TXN.VEHICLE_ID,
    VEH.VEHICLE_SK,
    TXN.CLIENT_ID,
    CLI.CLIENT_SK,
    TXN.TRANSACTION_DATETIME,
    TXN.TRANSACTION_DATE,
    TXN.MERCHANT_STATE,
    TXN.FUEL_PRODUCT,
    TXN.LITRES,
    TXN.GROSS_AMOUNT,
    TEL.DISTANCE_KM,
    CARD.VEHICLE_ID AS CARD_VEHICLE_ID,
    CARD.CLIENT_ID AS CARD_CLIENT_ID,
    TXN.SOURCE_RECORD_HASH
  FROM fuel_txn TXN
  LEFT JOIN CONFORMED.FACT_TELEMATICS_DAILY_SUMMARY TEL
    ON TEL.VEHICLE_ID = TXN.VEHICLE_ID
   AND TO_DATE(TEL.EVENT_DATE) = TXN.TRANSACTION_DATE
  LEFT JOIN CONFORMED.DIM_FUEL_CARD CARD
    ON CARD.FUEL_CARD_ID = TXN.FUEL_CARD_ID
   AND CARD.IS_CURRENT = TRUE
  LEFT JOIN CONFORMED.DIM_VEHICLE VEH
    ON VEH.VEHICLE_ID = TXN.VEHICLE_ID
   AND VEH.IS_CURRENT = TRUE
  LEFT JOIN CONFORMED.DIM_CLIENT CLI
    ON CLI.CLIENT_ID = TXN.CLIENT_ID
   AND CLI.IS_CURRENT = TRUE
),
scored AS (
  SELECT
    *,
    IFF(COALESCE(DISTANCE_KM, 0) > 0, GROSS_AMOUNT / NULLIF(DISTANCE_KM, 0), NULL) AS FUEL_COST_PER_KM,
    COUNT(*) OVER (
      PARTITION BY FUEL_CARD_ID
      ORDER BY TRANSACTION_DATETIME
      RANGE BETWEEN INTERVAL '7 DAY' PRECEDING AND CURRENT ROW
    ) AS TRANSACTION_FREQUENCY_7D,
    AVG(GROSS_AMOUNT) OVER (PARTITION BY FUEL_CARD_ID) AS AVG_GROSS_AMOUNT_BY_CARD,
    STDDEV(GROSS_AMOUNT) OVER (PARTITION BY FUEL_CARD_ID) AS STD_GROSS_AMOUNT_BY_CARD
  FROM txn_enriched
),
flags AS (
  SELECT
    *,
    TRANSACTION_FREQUENCY_7D > 1 AS MULTIPLE_FILL_FLAG,
    DISTANCE_KM IS NULL OR COALESCE(DISTANCE_KM, 0) <= 0 AS NO_USAGE_MATCH_FLAG,
    GROSS_AMOUNT > 250
      OR (
        STD_GROSS_AMOUNT_BY_CARD IS NOT NULL
        AND GROSS_AMOUNT > AVG_GROSS_AMOUNT_BY_CARD + (2 * STD_GROSS_AMOUNT_BY_CARD)
      ) AS HIGH_VALUE_TRANSACTION_FLAG,
    (
      CARD_VEHICLE_ID IS NOT NULL
      AND CARD_VEHICLE_ID <> VEHICLE_ID
    )
    OR (
      CARD_CLIENT_ID IS NOT NULL
      AND CARD_CLIENT_ID <> CLIENT_ID
    ) AS FUEL_CARD_VEHICLE_MISMATCH_FLAG
  FROM scored
)
SELECT
  FUEL_TRANSACTION_ID,
  FUEL_CARD_ID,
  VEHICLE_ID,
  VEHICLE_SK,
  CLIENT_ID,
  CLIENT_SK,
  TRANSACTION_DATETIME,
  TRANSACTION_DATE,
  MERCHANT_STATE,
  FUEL_PRODUCT,
  LITRES,
  GROSS_AMOUNT,
  DISTANCE_KM,
  FUEL_COST_PER_KM,
  TRANSACTION_FREQUENCY_7D,
  MULTIPLE_FILL_FLAG,
  NO_USAGE_MATCH_FLAG,
  HIGH_VALUE_TRANSACTION_FLAG,
  FUEL_CARD_VEHICLE_MISMATCH_FLAG,
  LEAST(
    100,
    IFF(HIGH_VALUE_TRANSACTION_FLAG, 30, 0)
      + IFF(NO_USAGE_MATCH_FLAG, 25, 0)
      + IFF(FUEL_CARD_VEHICLE_MISMATCH_FLAG, 30, 0)
      + IFF(MULTIPLE_FILL_FLAG, 15, 0)
  ) AS FUEL_ANOMALY_SCORE,
  ARRAY_TO_STRING(
    ARRAY_CONSTRUCT_COMPACT(
      IFF(HIGH_VALUE_TRANSACTION_FLAG, 'HIGH_VALUE_TRANSACTION', NULL),
      IFF(NO_USAGE_MATCH_FLAG, 'NO_USAGE_MATCH', NULL),
      IFF(FUEL_CARD_VEHICLE_MISMATCH_FLAG, 'CARD_VEHICLE_MISMATCH', NULL),
      IFF(MULTIPLE_FILL_FLAG, 'MULTIPLE_FILLS_7D', NULL)
    ),
    ','
  ) AS ANOMALY_REASON_CODES,
  'fuel_anomaly_rules_v0.1' AS FEATURE_VERSION,
  CURRENT_TIMESTAMP() AS SCORED_AT,
  COALESCE(TRY_TO_DATE('{batch_date}'), CURRENT_DATE()) AS BATCH_DATE,
  SOURCE_RECORD_HASH
FROM flags
""").collect()

    row_count = session.table("FEATURES.FEATURE_FUEL_ANOMALY_SCORE").count()
    return f"Wrote {row_count} rows to FEATURES.FEATURE_FUEL_ANOMALY_SCORE"
$$;

-- Example execution:
-- CALL FEATURES.BUILD_FEATURE_FUEL_ANOMALY_SCORE('2026-05-26');

CREATE TABLE IF NOT EXISTS AUDIT.FEATURE_TEST_RESULTS (
  CHECK_NAME VARCHAR,
  CHECK_VALUE NUMBER,
  EXPECTED_VALUE NUMBER,
  CHECK_STATUS VARCHAR,
  CHECKED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Run these checks after executing the procedure.
INSERT INTO AUDIT.FEATURE_TEST_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT
  'FEATURE_FUEL_ANOMALY_SCORE_ROWS',
  COUNT(*),
  (SELECT COUNT(*) FROM CONFORMED.FACT_FUEL_TRANSACTION),
  IFF(COUNT(*) = (SELECT COUNT(*) FROM CONFORMED.FACT_FUEL_TRANSACTION), 'passed', 'failed')
FROM FEATURES.FEATURE_FUEL_ANOMALY_SCORE;

INSERT INTO AUDIT.FEATURE_TEST_RESULTS (CHECK_NAME, CHECK_VALUE, EXPECTED_VALUE, CHECK_STATUS)
SELECT
  'FEATURE_FUEL_ANOMALY_SCORE_RANGE_FAILURES',
  COUNT(*),
  0,
  IFF(COUNT(*) = 0, 'passed', 'failed')
FROM FEATURES.FEATURE_FUEL_ANOMALY_SCORE
WHERE FUEL_ANOMALY_SCORE < 0
   OR FUEL_ANOMALY_SCORE > 100
   OR FUEL_ANOMALY_SCORE IS NULL;

SELECT *
FROM AUDIT.FEATURE_TEST_RESULTS
WHERE CHECK_NAME LIKE 'FEATURE_FUEL_ANOMALY%'
ORDER BY CHECKED_AT, CHECK_NAME;
